import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) =>
  StyleSheet.create({
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: theme.Spacing.lg,
    },
    modalContent: {
      width: '100%',
      maxHeight: '85%',
      backgroundColor: theme.Colors.surfaceContainerLowest,
      borderRadius: theme.Rounded.xl,
      borderWidth: 1,
      borderColor: theme.Colors.outline,
      overflow: 'hidden',
      shadowColor: 'black',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    desktopModal: {
      width: 600,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: theme.Spacing.lg,
      paddingVertical: 18,
      borderBottomWidth: 1,
      borderBottomColor: theme.Colors.outline,
    },
    ticketNum: {
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
      letterSpacing: 0.2,
    },
    modalTitle: {
      fontSize: theme.Typography.bodyLg?.fontSize || 18,
      fontWeight: '600',
      color: theme.Colors.onSurface,
      marginTop: 2,
    },
    closeButton: {
      minWidth: 44,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingContainer: {
      padding: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    scrollBody: {
      padding: theme.Spacing.lg,
    },
    badgesRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.Spacing.sm,
      marginBottom: 20,
    },
    badge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 10,
    },
    badgeText: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    infoCard: {
      backgroundColor: 'rgba(255, 255, 255, 0.45)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.65)',
      borderRadius: 20,
      padding: theme.Spacing.md,
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
      marginBottom: 10,
      letterSpacing: 0.2,
    },
    descriptionText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurface,
      lineHeight: 20,
    },
    metaGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: theme.Spacing.md,
      paddingTop: theme.Spacing.md,
      borderTopWidth: 1,
      borderTopColor: 'rgba(0, 104, 117, 0.1)',
      gap: theme.Spacing.md,
    },
    metaItem: {
      flex: 1,
      minWidth: 120,
    },
    metaLabel: {
      fontSize: theme.Typography.labelSmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      marginBottom: 2,
      fontWeight: '600',
    },
    metaValue: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
    },
    actionsContainer: {
      backgroundColor: 'rgba(255, 255, 255, 0.55)',
      borderWidth: 1.5,
      borderColor: 'rgba(255, 255, 255, 0.75)',
      borderRadius: 20,
      padding: theme.Spacing.md,
      marginBottom: 20,
    },
    actionButtonsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.Spacing.sm,
    },
    actionBtn: {
      minHeight: 44,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
    },
    btnInProg: {
      backgroundColor: theme.Colors.primary,
    },
    btnResolve: {
      backgroundColor: '#16a34a',
    },
    btnEscalate: {
      backgroundColor: '#f59e0b',
    },
    actionBtnText: {
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.surfaceContainerLowest,
    },
    escalateInputContainer: {
      marginTop: 12,
      borderTopWidth: 1,
      borderTopColor: 'rgba(0, 104, 117, 0.1)',
      paddingTop: 12,
    },
    escalateInput: {
      backgroundColor: 'rgba(255, 255, 255, 0.7)',
      borderWidth: 1,
      borderColor: 'rgba(0, 104, 117, 0.2)',
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurface,
      marginBottom: 10,
      minHeight: 50,
    },
    escalateActionButtons: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: theme.Spacing.sm,
    },
    cancelBtn: {
      minHeight: 44,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
    },
    cancelBtnText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontWeight: '600',
    },
    confirmEscalateBtn: {
      minHeight: 44,
      backgroundColor: theme.Colors.error,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
    },
    confirmEscalateText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.surfaceContainerLowest,
    },
    timelineSection: {
      marginTop: 10,
    },
    timelineItem: {
      flexDirection: 'row',
      marginBottom: theme.Spacing.md,
      gap: theme.Spacing.md,
    },
    timelineLineWrapper: {
      alignItems: 'center',
    },
    timelineDot: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: 'rgba(255,255,255,0.7)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    timelineLine: {
      width: 2,
      flex: 1,
      backgroundColor: 'rgba(0,104,117,0.1)',
      marginTop: theme.Spacing.xs,
    },
    timelineContent: {
      flex: 1,
      backgroundColor: 'rgba(255, 255, 255, 0.4)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.55)',
      borderRadius: 12,
      padding: 12,
    },
    timelineHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: theme.Spacing.xs,
    },
    authorName: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
    },
    timelineDate: {
      fontSize: theme.Typography.labelSmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontWeight: '600',
    },
    timelineBody: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurface,
      lineHeight: 18,
    },
    emptyTimelineText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontStyle: 'italic',
      textAlign: 'center',
      marginTop: 10,
    },
    commentInputWrapper: {
      flexDirection: 'row',
      padding: theme.Spacing.md,
      borderTopWidth: 1,
      borderTopColor: 'rgba(0, 104, 117, 0.1)',
      backgroundColor: 'rgba(255, 255, 255, 0.35)',
      alignItems: 'center',
      gap: 12,
    },
    commentInput: {
      flex: 1,
      backgroundColor: 'rgba(255, 255, 255, 0.65)',
      borderWidth: 1,
      borderColor: 'rgba(0, 104, 117, 0.15)',
      borderRadius: 18,
      paddingHorizontal: theme.Spacing.md,
      paddingVertical: 10,
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurface,
      maxHeight: 100,
    },
    sendButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.Colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sendButtonDisabled: {
      backgroundColor: 'rgba(0, 104, 117, 0.15)',
    },
  });
