/** Visit slots as generated by the backend from the property's visiting hours. */

export type TourSlotStatus =
  | 'AVAILABLE'
  /** Every place in the slot is taken. */
  | 'FULL'
  /** The landlord declined this slot for the phone that is verified in this tab. */
  | 'DECLINED'
  /** Past, inside the property's notice period, or blocked by the landlord. */
  | 'UNAVAILABLE';

export type TourSlot = {
  /** ISO instant the visit starts. */
  start: string;
  /** Start time in the property's timezone, `HH:mm`. */
  localTime: string;
  status: TourSlotStatus;
};

export type TourSlotDay = {
  /** `YYYY-MM-DD` in the property's timezone. */
  date: string;
  /** No visiting hours that day, or the whole day is blocked. */
  closed: boolean;
  slots: TourSlot[];
};

export type TourSlots = {
  propertyId: string;
  /** IANA timezone the times are in, e.g. `Asia/Kolkata`. */
  timezone: string;
  slotMinutes: number;
  days: TourSlotDay[];
};
