import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  root: { flex: 1 },
  safeArea: { flex: 1 },
  scrollContent: { gap: theme.Spacing.md },
  scrollContentDesktop: { paddingTop: 24, paddingHorizontal: 32, paddingBottom: 40, width: '100%' },

  desktopHeader: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: theme.Spacing.md, marginBottom: theme.Spacing.xs },
  kickerRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  kicker: { fontSize: theme.Typography.labelSmall.fontSize, fontWeight: '600', letterSpacing: 0.2, color: theme.Colors.primary },
  propertyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: theme.Spacing.sm,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: 'rgba(0,104,117,0.08)',
  },
  propertyBadgeText: { fontSize: theme.Typography.labelSmall.fontSize, fontWeight: '700', color: theme.Colors.primary },
  desktopTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: theme.Spacing.md, marginTop: 10 },
  desktopTitleWrapper: { flex: 1 },
  desktopTitle: { ...theme.Typography.headlineLg, color: theme.Colors.onSurface, letterSpacing: -0.5 },
  desktopSub: { fontSize: theme.Typography.bodyMedium.fontSize, color: theme.Colors.onSurfaceVariant, marginTop: theme.Spacing.xs, fontWeight: '600' },
  desktopActions: { flexDirection: 'row', alignItems: 'center', gap: theme.Spacing.md },

  btnPrimary: { borderRadius: 100, overflow: 'hidden' },
  btnPrimaryInner: { height: 46, paddingHorizontal: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: theme.Spacing.sm },
  btnText: { color: theme.Colors.surfaceContainerLowest, fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '600', letterSpacing: 0.5 },

  mobileHeader: { paddingHorizontal: theme.Spacing.md, paddingTop: theme.Spacing.md, paddingBottom: theme.Spacing.sm },
  mobileTitle: { ...theme.Typography.headlineMd, color: theme.Colors.onSurface, letterSpacing: -0.5 },
  mobileSub: { fontSize: theme.Typography.bodySmall.fontSize, color: theme.Colors.onSurfaceVariant, marginTop: 2, fontWeight: '600' },

  filterBar: { flexDirection: 'row', paddingHorizontal: theme.Spacing.md, gap: 12, alignItems: 'center', marginTop: 10 },
  filterBarDesktop: { paddingHorizontal: 0, marginTop: theme.Spacing.lg },
  searchWrapper: { flex: 1, position: 'relative' },
  searchIcon: { position: 'absolute', left: 14, top: 12, zIndex: 5 },
  searchInput: {
    height: 44,
    backgroundColor: isDark ? 'rgba(15, 23, 32, 0.6)' : 'rgba(255, 255, 255, 0.50)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    paddingLeft: 44,
    paddingRight: theme.Spacing.md,
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurface,
    fontWeight: '600',
    outlineWidth: 0,
  },
  propertySelectWrapper: { width: 190 },

  statsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.Spacing.md },
  statCard: {
    flex: 1,
    minWidth: 140,
    borderRadius: 20,
    padding: theme.Spacing.md,
    borderWidth: 1.5,
    borderColor: theme.Colors.glassStroke,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
  },
  statHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  statTitle: { fontSize: theme.Typography.labelSmall.fontSize, fontWeight: '600', color: theme.Colors.onSurfaceVariant, letterSpacing: 0.5 },
  statIcon: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  statVal: { fontSize: theme.Typography.headlineSmall.fontSize, fontWeight: '600', color: theme.Colors.onSurface },

  tabsRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.06)', marginTop: theme.Spacing.sm, paddingHorizontal: theme.Spacing.md },
  tabsRowDesktop: { paddingHorizontal: 0, marginTop: theme.Spacing.md },
  tabBtn: { paddingVertical: 12, paddingHorizontal: theme.Spacing.md, borderBottomWidth: 2, borderBottomColor: 'transparent', marginRight: theme.Spacing.md },
  activeTabBtn: { borderBottomColor: theme.Colors.primary },
  tabText: { fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '700', color: theme.Colors.onSurfaceVariant },
  activeTabText: { color: theme.Colors.primary, fontWeight: '600' },

  sectionCard: {
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: theme.Colors.glassStroke,
    backgroundColor: theme.Colors.glassFill,
    padding: theme.Spacing.lg,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    overflow: 'hidden',
  },
  sectionTitle: { fontSize: theme.Typography.bodyLg.fontSize, fontWeight: '600', color: theme.Colors.onSurface, marginBottom: theme.Spacing.md },

  gridContainer: { gap: theme.Spacing.md },
  gridContainerDesktop: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.Spacing.lg },
  gridItemDesktop: { width: '48%' },

  tabContentContainer: {
    width: '100%',
    gap: theme.Spacing.md,
  },
  leaseCard: {
    borderRadius: 20,
    width: '100%',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  propertyUnitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  cardTitle: { fontSize: theme.Typography.titleMedium.fontSize, fontWeight: '600', color: theme.Colors.onSurface },
  cardSubtitle: { fontSize: theme.Typography.bodySmall.fontSize, color: theme.Colors.onSurfaceVariant, marginTop: 2, fontWeight: '600' },

  infoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  infoCol: { flex: 1, minWidth: 120 },
  infoLabel: { fontSize: theme.Typography.labelSmall.fontSize - 2, fontWeight: '600', color: theme.Colors.onSurfaceVariant, letterSpacing: 0.5 },
  infoValue: { fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '700', color: theme.Colors.onSurface, marginTop: theme.Spacing.xs },

  actionRow: { flexDirection: 'row', gap: 12, marginTop: 6 },
  btnSecondary: {
    flex: 1,
    height: 42,
    borderWidth: 1.5,
    borderColor: theme.Colors.primary,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    backgroundColor: 'rgba(0,104,117,0.04)',
  },
  btnSecondaryText: { color: theme.Colors.primary, fontSize: theme.Typography.bodySmall.fontSize, fontWeight: '600' },

  btnActionDestructive: {
    flex: 1,
    height: 42,
    borderWidth: 1.5,
    borderColor: theme.Colors.error,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    backgroundColor: 'rgba(229,57,53,0.04)',
  },
  btnActionDestructiveText: { color: theme.Colors.error, fontSize: theme.Typography.bodySmall.fontSize, fontWeight: '600' },

  btnActionSuccess: {
    flex: 1,
    height: 42,
    borderRadius: 100,
    overflow: 'hidden',
  },
  btnActionSuccessInner: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  btnActionSuccessText: { color: theme.Colors.surfaceContainerLowest, fontSize: theme.Typography.bodySmall.fontSize, fontWeight: '600' },

  emptyContainer: { padding: 40, alignItems: 'center', justifyContent: 'center', gap: 12 },
  emptyText: { fontSize: theme.Typography.bodyLarge.fontSize, color: theme.Colors.onSurfaceVariant, fontWeight: '600' },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalCard: { width: '100%', backgroundColor: theme.Colors.surfaceContainerLowest, borderRadius: 28, overflow: 'hidden', borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.9)' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: theme.Spacing.lg, borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.06)' },
  modalKicker: { fontSize: theme.Typography.labelSmall.fontSize, fontWeight: '600', letterSpacing: 1, color: theme.Colors.onSurfaceVariant },
  modalTitle: { fontSize: theme.Typography.titleLarge.fontSize, fontWeight: '600', color: theme.Colors.onSurface, marginTop: theme.Spacing.xs },
  closeBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(0,0,0,0.03)', alignItems: 'center', justifyContent: 'center' },
  modalBody: { padding: theme.Spacing.lg, gap: theme.Spacing.md },
  modalFooter: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, padding: theme.Spacing.lg, borderTopWidth: 1, borderTopColor: 'rgba(0,0,0,0.06)' },

  cancelBtn: { minHeight: 44, justifyContent: 'center', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 20, borderRadius: 100 },
  cancelBtnText: { fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '600', color: theme.Colors.onSurfaceVariant },
  submitBtn: { borderRadius: 100, overflow: 'hidden' },
  submitBtnInner: { minHeight: 44, paddingVertical: 10, paddingHorizontal: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: theme.Spacing.sm },
  submitBtnText: { color: theme.Colors.surfaceContainerLowest, fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '600' },

  input: {
    height: 48,
    backgroundColor: 'rgba(0,0,0,0.02)',
    borderWidth: 1,
    borderColor: 'rgba(0,104,117,0.15)',
    borderRadius: 12,
    paddingHorizontal: theme.Spacing.md,
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurface,
    fontWeight: '600',
    outlineWidth: 0,
  },
  label: { fontSize: theme.Typography.labelSmall.fontSize, fontWeight: '600', color: theme.Colors.onSurfaceVariant, letterSpacing: 0.5 },

  // Pagination Styles
  paginationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: theme.Spacing.md,
    paddingHorizontal: theme.Spacing.xs,
    marginTop: theme.Spacing.sm,
  },
  paginationRowDesktop: {
    marginTop: theme.Spacing.md,
    paddingHorizontal: 0,
  },
  pageBtn: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: theme.Spacing.md,
    paddingVertical: 10,
    borderRadius: 100,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.9)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  pageBtnDisabled: {
    opacity: 0.5,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  pageBtnText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  pageBtnTextDisabled: {
    color: theme.Colors.onSurfaceVariant,
  },
  pageNumberPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  pageNumberText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  actionBtnOutline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.Spacing.xs,
    borderWidth: 1.5,
    borderColor: theme.Colors.primary,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: 'transparent',
  },
  actionBtnText: {
    color: theme.Colors.primary,
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
  },
  actionBtnPrimary: {
    borderRadius: 8,
    overflow: 'hidden',
  },
  actionBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.Spacing.xs,
    paddingVertical: 7,
    paddingHorizontal: 12,
  },
  actionBtnTextPrimary: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
  },
  actionBtnTextBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  forfeitText: {
    color: theme.Colors.error,
    fontWeight: '700',
    fontSize: theme.Typography.bodySmall.fontSize,
  },
  refundText: {
    color: theme.Colors.primary,
    fontWeight: '700',
    fontSize: theme.Typography.bodySmall.fontSize,
  },
  emptyState: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  emptyIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
    marginTop: theme.Spacing.sm,
  },
  emptySubtitle: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    textAlign: 'center',
    lineHeight: 20,
  },
  listContainer: {
    gap: theme.Spacing.md,
  },
  tenantAvatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: isDark ? 'rgba(0, 104, 117, 0.25)' : 'rgba(0, 104, 117, 0.08)',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(0, 104, 117, 0.35)' : 'rgba(0, 104, 117, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tenantAvatarText: {
    fontSize: theme.Typography.titleMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  tenantTextContainer: {
    flex: 1,
    minWidth: 0,
  },
  tenantName: {
    fontSize: theme.Typography.titleMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  tenantContact: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
    fontWeight: '500',
  },
  unitBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: isDark ? 'rgba(0, 104, 117, 0.25)' : 'rgba(0, 104, 117, 0.08)',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(0, 104, 117, 0.35)' : 'rgba(0, 104, 117, 0.15)',
  },
  unitBadgeText: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  noticeAlertBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: isDark ? 'rgba(239, 68, 68, 0.15)' : 'rgba(239, 68, 68, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.25)',
    marginTop: 10,
  },
  noticeAlertText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.error,
  },
  leaseDetailsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginVertical: 12,
  },
  detailItem: {
    flex: 1,
    minWidth: 95,
    padding: 10,
    borderRadius: 12,
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.03)' : 'rgba(0, 104, 117, 0.04)',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.06)' : 'rgba(0, 104, 117, 0.08)',
  },
  detailLabel: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 0.2,
  },
  detailValue: {
    fontSize: theme.Typography.titleMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
    marginTop: 4,
  },
  detailValueSecondary: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
    marginTop: 4,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 8,
    gap: 10,
  },
  footerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  leaseIdText: {
    fontSize: theme.Typography.labelSmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  mobileActionsContainer: {
    marginTop: 10,
    gap: 8,
  },
  cardFooterMobile: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  mobileActionsRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  tabsScrollView: {
    marginVertical: 14,
  },
  tabsScrollContent: {
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 4,
  },
  leaseActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  leaseActionsCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  unitChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: theme.Spacing.sm,
    borderRadius: 100,
    backgroundColor: 'rgba(0,0,0,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  unitChipSelected: {
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    borderColor: theme.Colors.primary,
  },
  unitChipText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  unitChipTextSelected: {
    color: theme.Colors.primary,
    fontWeight: '700',
  },
  twoCol: {
    flexDirection: 'row',
    gap: theme.Spacing.md,
    width: '100%',
  },
  actionBtnOutlineDanger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.Spacing.xs,
    borderWidth: 1.5,
    borderColor: theme.Colors.error,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: 'transparent',
  },
  actionBtnTextDanger: {
    color: theme.Colors.error,
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
  },
  paginationBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: theme.Spacing.md,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.06)',
  },
  paginationInfo: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  paginationControls: {
    flexDirection: 'row',
    gap: theme.Spacing.sm,
    alignItems: 'center',
  },
  leaseTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  statsRowDesktop: {
    flexDirection: 'row',
    gap: 20,
  },
  statCardDesktop: {
    minWidth: 220,
  },
  statIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    fontSize: theme.Typography.headlineMd.fontSize,
    fontWeight: '600',
    marginTop: 12,
  },
  statLabel: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 0.5,
    marginTop: theme.Spacing.xs,
  },
  statHelper: {
    fontSize: theme.Typography.bodySmall.fontSize - 2,
    color: theme.Colors.outline,
    marginTop: 2,
  },
  tabBar: {
    flexDirection: 'row',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
    paddingBottom: theme.Spacing.xs,
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
    paddingVertical: 10,
    paddingHorizontal: theme.Spacing.md,
    borderRadius: 100,
    overflow: 'hidden',
    position: 'relative',
  },
  tabActive: {},
  tabTextActive: {
    color: theme.Colors.onPrimary,
    fontWeight: '600',
  },
  tabBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 100,
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  tabBadgeActive: {
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  tabBadgeText: {
    fontSize: theme.Typography.labelSmall.fontSize - 2,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
  },
  tabBadgeTextActive: {
    color: theme.Colors.onPrimary,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: theme.Spacing.md,
    paddingVertical: 10,
    backgroundColor: theme.Colors.glassFill,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
  },
  panel: {
    borderRadius: 28,
    padding: theme.Spacing.lg,
    borderWidth: 1.5,
    borderColor: theme.Colors.glassStroke,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  loadingBox: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  leaseCardAlert: {
    borderColor: 'rgba(229,57,53,0.3)',
    backgroundColor: 'rgba(229,57,53,0.02)',
  },
  alertStripe: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 4,
  },
  title: {
    fontSize: theme.Typography.headlineMd.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
    letterSpacing: -0.5,
    marginTop: theme.Spacing.xs,
  },
  subtitle: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: theme.Spacing.xs,
    fontWeight: '600',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  createBtnWrapper: {
    borderRadius: 100,
    overflow: 'hidden',
  },
  createBtn: {
    height: 46,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.Spacing.sm,
  },
  createBtnText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  loadingMoreBox: {
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  loadingMoreText: {
    fontSize: theme.Typography.labelSmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '700',
  },
  scrollHintBox: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollHintText: {
    fontSize: theme.Typography.labelSmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
    opacity: 0.7,
  },
});
