import { Platform, StyleSheet } from 'react-native';
import { Theme } from '@/src/theme/Theme';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    height: '100%',
  },
  containerDesktop: {
    paddingTop: 16,
    paddingHorizontal: 28,
    paddingBottom: 24,
    width: '100%',
    height: '100%',
  },
  chatWorkspace: {
    flex: 1,
    height: '100%',
    borderRadius: 24,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    backgroundColor: theme.Colors.surfaceContainerLowest,
  },
  chatWorkspaceDesktop: {
    marginVertical: 0,
  },
  workspaceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.Spacing.lg,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: theme.Colors.outlineVariant,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    flexWrap: 'wrap',
    gap: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  aiOrbIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  workspaceTitle: {
    fontFamily: theme.Typography.headlineSmall.fontFamily,
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  modelBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    paddingHorizontal: 10,
    paddingVertical: theme.Spacing.xs,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 104, 117, 0.2)',
  },
  activeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.Colors.primary,
  },
  modelBadgeText: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  workspaceSubtitle: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
  },
  headerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 22,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
  },
  headerBtnText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
  },
  suggestionsContainer: {
    paddingHorizontal: theme.Spacing.lg,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.04)',
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.04)' : 'rgba(0, 0, 0, 0.02)',
  },
  suggestionsLabel: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    letterSpacing: 1.1,
    color: theme.Colors.onSurfaceVariant,
    marginBottom: theme.Spacing.sm,
  },
  suggestionsScroll: {
    gap: theme.Spacing.sm,
  },
  suggestionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 38,
    gap: 6,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    borderRadius: 19,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  suggestionChipText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  messagesList: {
    flex: 1,
  },
  messagesListContent: {
    paddingHorizontal: theme.Spacing.lg,
    paddingVertical: 20,
    gap: theme.Spacing.md,
  },
  messageRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  messageRowUser: {
    justifyContent: 'flex-end',
  },
  messageRowAssistant: {
    justifyContent: 'flex-start',
  },
  assistantAvatar: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 104, 117, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  bubbleWrapper: {
    maxWidth: '75%',
  },
  bubble: {
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  userBubble: {
    borderBottomRightRadius: 4,
  },
  assistantBubble: {
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    borderBottomLeftRadius: 4,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  userMessageText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    lineHeight: 21,
    fontWeight: '600',
    color: theme.Colors.surfaceContainerLowest,
  },
  assistantMessageText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    lineHeight: 22,
    color: theme.Colors.onSurface,
    fontWeight: '400',
  },
  loadingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  loadingText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  timestampText: {
    fontSize: theme.Typography.labelSmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: theme.Spacing.xs,
    paddingHorizontal: theme.Spacing.xs,
  },
  inputDock: {
    marginTop: 'auto',
    paddingHorizontal: theme.Spacing.lg,
    paddingTop: 12,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outlineVariant,
    backgroundColor: theme.Colors.surfaceContainerLowest,
  },
  attachmentsPreviewRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  attachmentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.08)' : 'rgba(0, 0, 0, 0.05)',
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    maxWidth: 220,
  },
  attachmentThumb: {
    width: 22,
    height: 22,
    borderRadius: 5,
  },
  attachmentName: {
    fontSize: theme.Typography.labelSmall.fontSize,
    color: theme.Colors.onSurface,
    fontWeight: '500',
    flexShrink: 1,
  },
  attachmentRemoveBtn: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.18)' : 'rgba(0, 0, 0, 0.1)',
  },
  attachButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.06)' : 'rgba(0, 0, 0, 0.04)',
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
  },
  bubbleAttachmentsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  bubbleImageAttachment: {
    width: 160,
    height: 110,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
  },
  bubbleFileAttachment: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  bubbleFileName: {
    fontSize: theme.Typography.labelSmall.fontSize,
    color: theme.Colors.surfaceContainerLowest,
    fontWeight: '600',
    maxWidth: 160,
  },
  inputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1.5,
    borderColor: 'rgba(0, 104, 117, 0.25)',
    borderRadius: 24,
    paddingHorizontal: theme.Spacing.md,
    paddingVertical: 6,
    gap: 12,
  },
  textInput: {
    flex: 1,
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurface,
    maxHeight: 100,
    minHeight: 40,
    paddingVertical: 6,
    borderWidth: 0,
    backgroundColor: 'transparent',
    outlineWidth: 0,
  },
  sendButton: {
    borderRadius: 22,
    overflow: 'hidden',
  },
  sendIconActive: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendIconDisabled: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.Colors.surfaceContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputHintRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: theme.Spacing.sm,
    paddingHorizontal: theme.Spacing.xs,
  },
  inputHint: {
    fontSize: theme.Typography.labelSmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
  charCount: {
    fontSize: theme.Typography.labelSmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
});
