import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  statCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: theme.Spacing.md,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.Surface.border,
    backgroundColor: theme.Colors.glassFill,
    flex: 1,
    minWidth: 140,
  },
  statCardDesktop: {
    minWidth: 200,
  },
  statIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statLabel: {
    fontSize: theme.Typography.labelSmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  statValue: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.onBackground,
    marginTop: 2,
  },
  desktopShell: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebar: {
    width: 260,
    height: '100%',
    paddingHorizontal: 20,
    paddingTop: theme.Spacing.xl,
    paddingBottom: theme.Spacing.lg,
    borderRightWidth: 1,
    borderRightColor: theme.Surface.border,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  sidebarBrand: {
    marginBottom: 54,
  },
  sidebarBrandTitle: {
    fontSize: theme.Typography.displaySmall.fontSize,
    fontWeight: '600',
    lineHeight: 40,
    color: theme.Colors.primary,
  },
  sidebarBrandSub: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
    letterSpacing: 2,
    color: theme.Colors.onSurfaceVariant,
    marginTop: theme.Spacing.xs,
  },
  sidebarNav: {
    gap: 14,
  },
  sidebarLink: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.md,
    paddingHorizontal: 18,
    borderRadius: theme.Rounded.lg,
  },
  sidebarLinkActive: {
    backgroundColor: 'rgba(0, 224, 255, 0.10)',
    borderRightWidth: 4,
    borderRightColor: theme.Colors.primaryContainer,
  },
  sidebarLinkText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    letterSpacing: 1.6,
    color: theme.Colors.onSurface,
  },
  sidebarLinkTextActive: {
    color: theme.Colors.primary,
  },
  sidebarFooter: {
    marginTop: 'auto',
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outlineVariant,
    paddingTop: 28,
    gap: 10,
  },
  upgradeButton: {
    borderRadius: theme.Rounded.lg,
    overflow: 'hidden',
    marginBottom: 14,
    shadowColor: theme.Colors.secondary,
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  upgradeGradient: {
    paddingVertical: theme.Spacing.md,
    alignItems: 'center',
  },
  upgradeText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
  },
  desktopMain: {
    flex: 1,
  },
  topbar: {
    minHeight: 82,
    paddingHorizontal: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: theme.Surface.border,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  topbarTabs: {
    flexDirection: 'row',
    gap: 34,
    alignItems: 'center',
  },
  topbarTab: {
    fontSize: theme.Typography.bodyLg.fontSize,
    color: theme.Colors.onSurface,
  },
  topbarTabActive: {
    color: theme.Colors.primary,
    borderBottomWidth: 2,
    borderBottomColor: theme.Colors.primaryContainer,
    paddingBottom: theme.Spacing.sm,
  },
  topbarRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  searchBox: {
    width: 320,
    height: 50,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.Surface.border,
    backgroundColor: theme.Colors.glassFill,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 18,
    overflow: 'hidden',
  },
  searchPlaceholder: {
    fontSize: theme.Typography.bodyLarge.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
  topIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 3,
    borderColor: theme.Colors.primaryContainer,
    backgroundColor: theme.Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: theme.Colors.surfaceContainerLowest,
    fontWeight: '600',
    fontSize: theme.Typography.bodyLg.fontSize,
  },
  desktopContent: {
    paddingHorizontal: 32,
    paddingTop: 24,
    paddingBottom: 40,
  },
  desktopInner: {
    width: '100%',
    flex: 1,
  },
  propertyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 34,
    alignItems: 'stretch',
  },
  propertyGridItem: {
    width: '100%',
  },
  desktopFooter: {
    marginTop: 70,
    paddingTop: 26,
    borderTopWidth: 1,
    borderTopColor: theme.Surface.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 42,
  },
  footerBrand: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
    marginRight: 22,
  },
  footerLink: {
    fontSize: theme.Typography.bodySmall.fontSize,
    letterSpacing: 1.3,
    color: theme.Colors.onSurface,
  },
  footerCopy: {
    marginLeft: 'auto',
    color: theme.Colors.outline,
    fontSize: theme.Typography.bodyMedium.fontSize,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  mobileHeader: {
    paddingHorizontal: theme.Spacing.lg,
    paddingVertical: theme.Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'transparent',
  },
  mobileBrand: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  mobileAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.Colors.inverseSurface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: theme.Colors.primaryContainer,
  },
  mobileAvatarText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  headerTitle: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
    letterSpacing: 1,
  },
  compactHeaderTitle: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.onBackground,
  },
  menuButton: {
    padding: 5,
  },
  notificationButton: {
    padding: 5,
    position: 'relative',
  },
  logoutButton: {
    padding: 5,
  },
  notificationBadge: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.Colors.error,
  },
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 160,
  },
  titleContainer: {
    marginTop: theme.Spacing.md,
    marginBottom: theme.Spacing.lg,
  },
  desktopTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  mobileTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  countBadge: {
    backgroundColor: `${theme.Colors.primary}18`,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  countBadgeText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  mobileAddBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  mobileAddFooterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: theme.Colors.outlineVariant,
    borderStyle: 'dashed',
    backgroundColor: theme.Colors.surfaceContainerLow,
    marginTop: 12,
    marginBottom: 20,
  },
  mobileAddFooterText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  headerAddButtonWrapper: {
    borderRadius: 19,
    overflow: 'hidden',
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 2,
  },
  headerAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    height: 38,
    paddingHorizontal: 18,
  },
  headerAddButtonText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.surfaceContainerLowest,
    letterSpacing: 0.5,
  },
  largeTitleContainer: {
    marginBottom: 20,
  },
  titleLine: {
    ...theme.Typography.headlineXl,
    color: theme.Colors.onBackground,
    lineHeight: 52,
    letterSpacing: -1,
  },
  mainTitle: {
    ...theme.Typography.headlineLg,
    lineHeight: 38,
    color: theme.Colors.onBackground,
  },
  subtitle: {
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '400',
    lineHeight: 24,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 6,
    maxWidth: 620,
  },
  mobileSearchRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 30,
  },
  mobileSearchBox: {
    flex: 1,
    height: 50,
    borderRadius: theme.Rounded.md,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    overflow: 'hidden',
  },
  mobileSearchText: {
    fontSize: theme.Typography.bodyLarge.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
  searchInput: {
    flex: 1,
    height: '100%',
    fontSize: theme.Typography.bodyLarge.fontSize,
    color: theme.Colors.onBackground,
    padding: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    outlineWidth: 0,
  },
  mobileFilterButtonWrapper: {
    width: 50,
    height: 50,
    borderRadius: theme.Rounded.md,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    overflow: 'hidden',
  },
  mobileFilterButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 22,
    flexWrap: 'wrap',
  },
  desktopStatusStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 14,
    marginBottom: 4,
  },
  desktopStatusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
  },
  desktopStatusChipText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  manageButtonWrapperMobile: {
    marginHorizontal: theme.Spacing.lg,
    marginBottom: theme.Spacing.lg,
    shadowColor: theme.Colors.accentGradientEnd,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  manageButtonWrapperDesktop: {
    flex: 1,
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 0,
  },
  manageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 56,
    gap: theme.Spacing.sm,
  },
  emptyButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
  },
  manageButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  addNewCard: {
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 2,
    borderColor: theme.Surface.border,
    borderStyle: 'dashed',
    borderRadius: theme.Rounded.xl,
    padding: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  addNewCardDesktop: {
    width: '100%',
    minHeight: 180,
    marginTop: 0,
    backgroundColor: theme.Colors.glassFill,
    borderColor: theme.Surface.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
    padding: theme.Spacing.lg,
  },
  plusIconWrapper: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: theme.Colors.surfaceContainerLow,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  addNewTitle: {
    fontSize: theme.Typography.bodyLg.fontSize,
    fontWeight: '700',
    color: theme.Colors.onBackground,
    marginBottom: 5,
  },
  addNewSubtitle: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyCard: {
    backgroundColor: theme.Colors.glassFill,
    borderRadius: 24,
    padding: 30,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.Surface.border,
    shadowColor: theme.Colors.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 30,
    overflow: 'hidden',
  },
  emptyIconCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: theme.Colors.surfaceContainerLow,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '700',
    color: theme.Colors.onBackground,
    marginBottom: 10,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: theme.Typography.bodyLarge.fontSize,
    color: theme.Colors.onSurfaceVariant,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 30,
    paddingHorizontal: 20,
  },
  createPropertyButton: {
    width: '100%',
    borderRadius: 100,
    overflow: 'hidden',
    marginBottom: 25,
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 5,
  },
  createPropertyGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    gap: 10,
  },
  createPropertyText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '600',
    letterSpacing: 1,
  },
  learnMoreContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  learnMoreText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.primary,
    letterSpacing: 0.5,
  },
  broadcastButtonWrapper: {
    borderRadius: 100,
    overflow: 'hidden',
  },
  broadcastButtonWrapperMobile: {
    marginHorizontal: theme.Spacing.lg,
    marginBottom: 20,
  },
  broadcastButtonWrapperDesktop: {
    flex: 1,
    marginHorizontal: 0,
    marginBottom: 0,
    borderRadius: 100,
  },
  broadcastButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    gap: theme.Spacing.sm,
    borderWidth: 1.5,
    borderColor: theme.Colors.primary,
    borderRadius: 100,
    backgroundColor: theme.Colors.primaryContainer,
  },
  broadcastButtonText: {
    color: theme.Colors.primary,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  composerOverlay: {
    flex: 1,
    backgroundColor: theme.Surface.overlay,
    justifyContent: 'flex-end',
  },
  composerSheet: {
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '92%',
    paddingTop: 12,
    shadowColor: theme.Surface.shadowColor,
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 24,
  },
  composerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: theme.Spacing.lg,
    paddingTop: 20,
    paddingBottom: theme.Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.Colors.outlineVariant,
  },
  composerTitle: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  composerSubtitle: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 3,
  },
  composerScroll: {
    paddingHorizontal: theme.Spacing.lg,
    paddingTop: 20,
  },
  composerLabel: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: theme.Colors.onSurfaceVariant,
    marginBottom: theme.Spacing.sm,
    marginTop: theme.Spacing.md,
  },
  composerInput: {
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    borderRadius: 12,
    paddingHorizontal: theme.Spacing.md,
    paddingVertical: 14,
    fontSize: theme.Typography.bodyLarge.fontSize,
    color: theme.Colors.onSurface,
    backgroundColor: theme.Colors.glassFill,
  },
  composerTextarea: {
    minHeight: 110,
    paddingTop: 14,
  },
  chipRow: {
    flexDirection: 'row',
    marginBottom: theme.Spacing.xs,
  },
  chip: {
    paddingHorizontal: theme.Spacing.md,
    paddingVertical: theme.Spacing.sm,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: theme.Colors.outlineVariant,
    backgroundColor: theme.Colors.glassFill,
    marginRight: 10,
    flexShrink: 0,
  },
  chipActive: {
    backgroundColor: theme.Colors.primary,
    borderColor: theme.Colors.primary,
  },
  chipText: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '700',
    letterSpacing: 0.8,
    color: theme.Colors.primary,
  },
  chipTextActive: {
    color: theme.Colors.onPrimary,
  },
  composerSendBtn: {
    margin: 20,
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: theme.Colors.accentGradientEnd,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 14,
    elevation: 8,
  },
  composerSendGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    gap: 10,
  },
  composerSendText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '600',
    letterSpacing: 1.2,
  },
  desktopSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: theme.Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    borderRadius: 20,
    paddingHorizontal: 12,
    height: 40,
    width: 280,
  },
  desktopSearchInput: {
    flex: 1,
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurface,
    paddingVertical: 0,
  },
});
