import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: theme.Spacing.xl,
    paddingTop: theme.Spacing.sm,
    paddingBottom: 100,
  },
  header: {
    paddingHorizontal: theme.Spacing.lg,
    paddingTop: theme.Spacing.sm,
    paddingBottom: theme.Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.md,
  },
  compactTitleContainer: {
    flex: 1,
    paddingBottom: theme.Spacing.md,
  },
  compactTitleText: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: theme.Spacing.md,
  },
  largeTitleContainer: {
    marginBottom: 20,
  },
  titleLine: {
    fontSize: theme.Typography.headlineXl.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
    lineHeight: 52,
    letterSpacing: -1,
  },
  cardContainer: {
    borderRadius: theme.Rounded.xl,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    overflow: 'hidden',
    padding: theme.Spacing.lg,
    marginBottom: 30,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  description: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    lineHeight: 22,
    marginBottom: theme.Spacing.lg,
    fontWeight: '500',
  },
  formContainer: {
    gap: 20,
  },
  inputGroup: {
    gap: theme.Spacing.sm,
  },
  label: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 1,
  },
  inputWrapper: {
    position: 'relative',
    width: '100%',
  },
  input: {
    height: 48,
    backgroundColor: theme.Colors.glassFill,
    borderRadius: 12,
    paddingHorizontal: theme.Spacing.md,
    fontSize: theme.Typography.bodyLarge.fontSize,
    color: theme.Colors.onSurface,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    fontWeight: '600',
    outlineWidth: 0,
  },
  inputWithIconRight: {
    height: 48,
    backgroundColor: theme.Colors.glassFill,
    borderRadius: 12,
    paddingLeft: theme.Spacing.md,
    paddingRight: 46,
    fontSize: theme.Typography.bodyLarge.fontSize,
    color: theme.Colors.onSurface,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    fontWeight: '600',
    width: '100%',
    outlineWidth: 0,
  },
  inputIconRight: {
    position: 'absolute',
    right: 16,
    top: 14,
  },
  row: {
    flexDirection: 'row',
    gap: theme.Spacing.md,
  },
  submitButton: {
    borderRadius: 100,
    overflow: 'hidden',
    marginTop: 10,
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  submitGradient: {
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.Spacing.sm,
  },
  submitText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '600',
    letterSpacing: 1,
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
    backgroundColor: 'rgba(229, 57, 53, 0.08)',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(229, 57, 53, 0.15)',
    marginBottom: 20,
  },
  errorText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.error,
    fontWeight: '600',
    flex: 1,
  },

  // Desktop Shell Styles
  desktopShell: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebar: {
    width: 260,
    height: '100%',
    paddingHorizontal: 20,
    paddingTop: theme.Spacing.xl,
    paddingBottom: theme.Spacing.lg,
    borderRightWidth: 1,
    borderRightColor: theme.Surface.border,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  sidebarBrand: {
    marginBottom: 54,
  },
  sidebarBrandTitle: {
    fontSize: theme.Typography.displaySmall.fontSize,
    fontWeight: '600',
    lineHeight: 40,
    color: theme.Colors.primary,
  },
  sidebarBrandSub: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    letterSpacing: 2,
    color: theme.Colors.onSurfaceVariant,
    marginTop: theme.Spacing.xs,
  },
  sidebarNav: {
    gap: 14,
  },
  sidebarLink: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.md,
    paddingHorizontal: 18,
    borderRadius: theme.Rounded.lg,
  },
  sidebarLinkActive: {
    backgroundColor: 'rgba(0, 224, 255, 0.10)',
    borderRightWidth: 4,
    borderRightColor: theme.Colors.primaryContainer,
  },
  sidebarLinkText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    letterSpacing: 1.6,
    color: theme.Colors.onSurface,
  },
  sidebarLinkTextActive: {
    color: theme.Colors.primary,
  },
  sidebarFooter: {
    marginTop: 'auto',
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outlineVariant,
    paddingTop: 28,
    gap: 10,
  },
  upgradeButton: {
    borderRadius: theme.Rounded.lg,
    overflow: 'hidden',
    marginBottom: 14,
    shadowColor: theme.Colors.secondary,
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  upgradeGradient: {
    paddingVertical: theme.Spacing.md,
    alignItems: 'center',
  },
  upgradeText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
  },
  desktopMain: {
    flex: 1,
  },
  desktopContent: {
    paddingHorizontal: 40,
    paddingBottom: 40,
  },
  desktopInner: {
    maxWidth: 1080,
    width: '100%',
    alignSelf: 'center',
    paddingTop: theme.Spacing.lg,
  },
  desktopHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: theme.Spacing.xl,
  },
  largeTitleContainerDesktop: {
    flex: 1,
  },
  titleLineDesktop: {
    ...theme.Typography.headlineLg,
    color: theme.Colors.onSurface,
  },
  subtitleDesktop: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: theme.Spacing.xs,
    fontWeight: '600',
  },
  desktopSaveButtonWrapper: {
    borderRadius: 23,
    overflow: 'hidden',
  },
  desktopSaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: theme.Spacing.lg,
    height: 46,
    gap: theme.Spacing.sm,
  },
  desktopSaveButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    letterSpacing: 1,
  },
  desktopFormContainer: {
    flexDirection: 'row',
    gap: theme.Spacing.xl,
    alignItems: 'flex-start',
  },
  desktopFormLeft: {
    flex: 1.5,
  },
  desktopFormRight: {
    flex: 1,
  },
  amenitiesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.Spacing.sm,
    marginTop: theme.Spacing.sm,
  },
  amenityChip: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: theme.Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
  },
  amenityChipSelected: {
    backgroundColor: theme.Colors.primaryContainer,
    borderColor: theme.Colors.primary,
  },
  amenityChipText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
  },
  amenityChipTextSelected: {
    color: theme.Colors.onPrimaryContainer,
  },
});
