import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 56,
    zIndex: 999,
    borderBottomWidth: 1.5,
    borderBottomColor: 'rgba(255, 255, 255, 0.45)',
    overflow: 'hidden',
  },
  headerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.Spacing.md,
  },
  titleWrapper: {
    flex: 1,
    alignItems: 'center',
  },
  compactTitleText: {
    fontSize: theme.Typography.bodyLg.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: theme.Spacing.md,
  },
  scrollContent: {
    paddingHorizontal: theme.Spacing.lg,
    paddingBottom: 40,
  },
  card: {
    borderRadius: theme.Rounded.xl,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    overflow: 'hidden',
    padding: theme.Spacing.lg,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: theme.Typography.labelSmall.fontSize,
    color: theme.Colors.primary,
    fontWeight: '600',
    letterSpacing: 1.5,
    marginBottom: 20,
  },
  inputGroup: {
    marginBottom: 18,
    gap: theme.Spacing.sm,
  },
  label: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 1,
  },
  input: {
    height: 48,
    backgroundColor: theme.Colors.glassFill,
    borderRadius: 12,
    paddingHorizontal: theme.Spacing.md,
    fontSize: theme.Typography.bodyLarge.fontSize,
    color: theme.Colors.onSurface,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    fontWeight: '600',
    outlineWidth: 0,
  },
  inputWithIcon: {
    height: 48,
    backgroundColor: theme.Colors.glassFill,
    borderRadius: 12,
    paddingLeft: theme.Spacing.md,
    paddingRight: 46,
    fontSize: theme.Typography.bodyLarge.fontSize,
    color: theme.Colors.onSurface,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    fontWeight: '600',
    width: '100%',
    outlineWidth: 0,
  },
  inputWrapper: {
    position: 'relative',
    width: '100%',
  },
  inputIcon: {
    position: 'absolute',
    right: 16,
    top: 14,
  },
  row: {
    flexDirection: 'row',
    gap: theme.Spacing.md,
  },
  divider: {
    height: 1.5,
    backgroundColor: theme.Colors.outlineVariant,
    marginVertical: 26,
    opacity: 0.6,
  },
  saveButtonWrapper: {
    borderRadius: 100,
    overflow: 'hidden',
    marginTop: 10,
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  saveButton: {
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.Spacing.sm,
  },
  saveButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '600',
    letterSpacing: 1,
  },
  configButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: theme.Spacing.md,
    backgroundColor: theme.Colors.glassFill,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    gap: theme.Spacing.md,
  },
  configIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: isDark ? 'rgba(0, 212, 255, 0.15)' : 'rgba(0, 104, 117, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  configTextWrapper: {
    flex: 1,
  },
  configTitle: {
    fontSize: theme.Typography.bodyLg.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  configSubtitle: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
  },

  // Desktop Shell Styles
  desktopShell: {
    flex: 1,
    flexDirection: 'row',
  },
  sidebar: {
    width: 260,
    height: '100%',
    paddingHorizontal: 20,
    paddingTop: theme.Spacing.xl,
    paddingBottom: theme.Spacing.lg,
    borderRightWidth: 1,
    borderRightColor: theme.Surface.border,
    backgroundColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  sidebarBrand: {
    marginBottom: 54,
  },
  sidebarBrandTitle: {
    fontSize: theme.Typography.displaySmall.fontSize,
    fontWeight: '600',
    lineHeight: 40,
    color: theme.Colors.primary,
  },
  sidebarBrandSub: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    letterSpacing: 2,
    color: theme.Colors.onSurfaceVariant,
    marginTop: theme.Spacing.xs,
  },
  sidebarNav: {
    gap: 14,
  },
  sidebarLink: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.md,
    paddingHorizontal: 18,
    borderRadius: theme.Rounded.lg,
  },
  sidebarLinkActive: {
    backgroundColor: 'rgba(0, 224, 255, 0.10)',
    borderRightWidth: 4,
    borderRightColor: theme.Colors.primaryContainer,
  },
  sidebarLinkText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    letterSpacing: 1.6,
    color: theme.Colors.onSurface,
  },
  sidebarLinkTextActive: {
    color: theme.Colors.primary,
  },
  sidebarFooter: {
    marginTop: 'auto',
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outlineVariant,
    paddingTop: 28,
    gap: 10,
  },
  upgradeButton: {
    borderRadius: theme.Rounded.lg,
    overflow: 'hidden',
    marginBottom: 14,
    shadowColor: theme.Colors.secondary,
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  upgradeGradient: {
    paddingVertical: theme.Spacing.md,
    alignItems: 'center',
  },
  upgradeText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
  },
  desktopMain: {
    flex: 1,
  },
  desktopContent: {
    paddingHorizontal: 40,
    paddingBottom: 40,
  },
  desktopInner: {
    maxWidth: 1140,
    width: '100%',
    alignSelf: 'center',
    paddingTop: theme.Spacing.lg,
  },
  desktopHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: theme.Spacing.xl,
  },
  largeTitleContainerDesktop: {
    flex: 1,
  },
  titleLineDesktop: {
    ...theme.Typography.headlineLg,
    color: theme.Colors.onSurface,
  },
  subtitleDesktop: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: theme.Spacing.xs,
    fontWeight: '600',
  },
  desktopSaveButtonWrapper: {
    borderRadius: theme.Rounded.md,
    overflow: 'hidden',
  },
  desktopSaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: theme.Spacing.lg,
    height: 46,
    gap: theme.Spacing.sm,
    backgroundColor: theme.Colors.primary,
    borderRadius: theme.Rounded.md,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  desktopSaveButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
  },
  desktopFormContainer: {
    flexDirection: 'row',
    gap: theme.Spacing.xl,
    alignItems: 'flex-start',
  },
  desktopFormLeft: {
    flex: 1.5,
  },
  desktopFormRight: {
    flex: 1.2,
  },
  desktop3DPreviewCard: {
    borderRadius: theme.Rounded.xl,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    padding: theme.Spacing.lg,
    gap: theme.Spacing.md,
  },
  desktopPreviewLabel: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
    letterSpacing: 1.2,
  },
  desktop3DContainer: {
    height: 380,
    backgroundColor: isDark ? 'rgba(0, 0, 0, 0.25)' : 'rgba(255, 255, 255, 0.35)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  resetButtonOverlay: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    padding: theme.Spacing.sm,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 999,
    zIndex: 10,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  previewInfoRow: {
    marginTop: theme.Spacing.sm,
  },
  previewName: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
    marginBottom: theme.Spacing.xs,
  },
  previewAddress: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 3,
    borderColor: theme.Colors.primaryContainer,
    backgroundColor: theme.Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: theme.Colors.surfaceContainerLowest,
    fontWeight: '600',
    fontSize: theme.Typography.bodyLg.fontSize,
  },
  amenitiesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.Spacing.sm,
    marginTop: theme.Spacing.sm,
  },
  amenityChip: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: theme.Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
  },
  amenityChipSelected: {
    backgroundColor: theme.Colors.primaryContainer,
    borderColor: theme.Colors.primary,
  },
  amenityChipText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
  },
  amenityChipTextSelected: {
    color: theme.Colors.onPrimaryContainer,
  },
  multiBlockNoticeCard: {
    padding: theme.Spacing.md,
    borderRadius: theme.Rounded.lg,
    backgroundColor: theme.Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.md,
    marginBottom: 18,
  },
  multiBlockNoticeIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.Colors.primaryContainer,
    justifyContent: 'center',
    alignItems: 'center',
  },
  multiBlockNoticeTitle: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurface,
  },
  multiBlockNoticeSubtitle: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    lineHeight: 18,
  },
  multiBlockManageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: theme.Rounded.md,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
  },
  multiBlockManageButtonText: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
});
