import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  gradient: {
    flex: 1,
    backgroundColor: theme.Colors.background,
  },
  safeArea: {
    flex: 1,
  },
  headerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 56,
    zIndex: 999,
    borderBottomWidth: 1,
    borderBottomColor: theme.Colors.outline,
    backgroundColor: theme.Colors.background,
    overflow: 'hidden',
  },
  headerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.Spacing.md,
  },
  titleWrapper: {
    flex: 1,
    alignItems: 'center',
  },
  compactTitleText: {
    fontSize: theme.Typography.bodyLg.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
    justifyContent: 'center',
    alignItems: 'center',
  },
  largeTitleContainer: {
    marginBottom: 20,
  },
  titleContainer: {},
  titleLine: {
    fontSize: theme.Typography.headlineMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
    lineHeight: 36,
    letterSpacing: -0.4,
  },
  propertyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.Colors.surfaceContainerLow,
    paddingRight: theme.Spacing.md,
    paddingLeft: 6,
    paddingVertical: 6,
    borderRadius: 100,
    alignSelf: 'flex-start',
    marginTop: 12,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
  },
  propertyIconWrapper: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.Spacing.sm,
  },
  propertyNameLabel: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: theme.Spacing.xl,
    paddingTop: 20,
    paddingBottom: 100,
  },
  floorsList: {
    gap: theme.Spacing.md,
  },
  floorCard: {
    borderRadius: theme.Rounded.lg,
    padding: theme.Spacing.lg,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    shadowColor: theme.Colors.outline,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 1,
  },
  floorCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  floorTitle: {
    fontSize: theme.Typography.headlineSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  configBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: theme.Rounded.sm,
  },
  configBadgeUnconfigured: {
    backgroundColor: theme.Colors.errorContainer,
    borderWidth: 1,
    borderColor: theme.Colors.error,
  },
  configBadgeConfigured: {
    backgroundColor: theme.Colors.successContainer,
    borderWidth: 1,
    borderColor: theme.Colors.success,
  },
  configBadgeText: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
  },
  configBadgeTextUnconfigured: {
    color: theme.Colors.error,
  },
  configBadgeTextConfigured: {
    color: theme.Colors.success,
  },
  floorStats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 16,
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
  },
  statText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '500',
  },
  actionButton: {
    minHeight: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: theme.Colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: theme.Spacing.sm,
    backgroundColor: 'transparent',
  },
  actionButtonText: {
    color: theme.Colors.primary,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
  },
  generatePanel: {
    marginTop: 10,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outline,
    gap: theme.Spacing.md,
  },
  generatePanelTitle: {
    fontSize: theme.Typography.bodyLg.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },

  // Desktop Shell Styles
  desktopShell: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: theme.Colors.background,
  },
  desktopMain: {
    flex: 1,
  },
  desktopContent: {
    paddingHorizontal: 40,
    paddingBottom: 40,
  },
  desktopInner: {
    maxWidth: 1140,
    width: '100%',
    alignSelf: 'center',
    paddingTop: theme.Spacing.lg,
  },
  desktopHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: theme.Spacing.md,
    marginBottom: theme.Spacing.xl,
  },
  backButtonBadge: {
    padding: 10,
    borderRadius: 14,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleLineDesktop: {
    ...theme.Typography.headlineLg,
    color: theme.Colors.onSurface,
    letterSpacing: -0.5,
  },
  subtitleDesktop: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
    fontWeight: '500',
  },
  desktopFloorsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.Spacing.lg,
  },
  desktopFloorCardWrapper: {
    width: '31%',
    minWidth: 320,
  },
  quickCreateRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    width: '100%',
  },
  quickCreateInput: {
    flex: 1,
    backgroundColor: theme.Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
    borderRadius: theme.Rounded.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurface,
  },
  quickGenerateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: theme.Colors.primary,
    paddingHorizontal: theme.Spacing.md,
    paddingVertical: 11,
    borderRadius: theme.Rounded.sm,
  },
  quickGenerateButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
  },
  floorCardDesktop: {
    width: '31%',
    minWidth: 320,
  },
  floorNumberBox: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.Colors.surfaceContainerLow,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.Spacing.md,
  },
  floorNumberText: {
    fontSize: theme.Typography.headlineSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  floorInfo: {
    flex: 1,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
    marginTop: theme.Spacing.xs,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.Spacing.sm,
    paddingVertical: theme.Spacing.xs,
    borderRadius: 6,
    gap: theme.Spacing.xs,
  },
  statusConfigured: {
    backgroundColor: theme.Colors.successContainer,
    borderWidth: 1,
    borderColor: theme.Colors.success,
  },
  statusNotConfigured: {
    backgroundColor: theme.Colors.errorContainer,
    borderWidth: 1,
    borderColor: theme.Colors.error,
  },
  statusText: {
    fontSize: theme.Typography.labelSmall.fontSize - 2,
    fontWeight: '600',
  },
  textConfigured: {
    color: theme.Colors.success,
  },
  textNotConfigured: {
    color: theme.Colors.error,
  },
  unitCountText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '500',
  },
  actionButtonWrapper: {
    borderRadius: theme.Rounded.md,
    overflow: 'hidden',
    marginTop: 12,
  },
  quickCreateSection: {
    marginTop: theme.Spacing.md,
    paddingTop: theme.Spacing.md,
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outline,
  },
  quickCreateTitle: {
    fontSize: theme.Typography.labelSmall.fontSize - 2,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
    marginBottom: theme.Spacing.sm,
  },
  floorsGridDesktop: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.Spacing.lg,
  },
});
