'use client';

import { useEffect, useMemo } from 'react';
import { Controller, useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { User, Phone, Mail, Calendar, Clock, ArrowRight, CheckCircle, Globe } from 'lucide-react';
import { CreateLeadRequest } from '@/types/lead';
import { TourSlots } from '@/types/tourSlot';
import { DateStrip } from '@/components/ui/DateStrip';
import { TimeSlotPicker } from '@/components/ui/TimeSlotPicker';
import { Skeleton } from '@/components/ui/Skeleton';
import { findFirstBookableSlot, findSlot, formatTimezone, isVisitorTimezone } from '@/utils/visitSlots';

const tourSchema = z.object({
  prospectName: z.string().min(2, 'Name must be at least 2 characters'),
  prospectPhone: z
    .string()
    .regex(/^[6-9]\d{9}$/, 'Please enter a valid 10-digit Indian mobile number'),
  prospectEmail: z.string().email('Invalid email address').optional().or(z.literal('')),
  preferredDate: z.string().min(1, 'Please select a preferred visit date'),
  preferredTime: z.string().min(1, 'Please select a preferred visit time'),
});

type TourFormData = z.infer<typeof tourSchema>;

type Props = {
  onSubmitLead: (data: CreateLeadRequest) => void;
  loading: boolean;
  /** Phone number already verified via OTP in this session; submitting with it skips the OTP step. */
  verifiedPhone?: string | null;
  /** Visit slots the property currently offers, as generated by the backend. */
  slots: TourSlots | null;
  isLoadingSlots: boolean;
};

export function TourRequestForm({ onSubmitLead, loading, verifiedPhone = null, slots, isLoadingSlots }: Props) {
  const {
    register,
    control,
    handleSubmit,
    watch,
    getValues,
    setValue,
    formState: { errors, isSubmitted },
  } = useForm<TourFormData>({
    resolver: zodResolver(tourSchema),
    defaultValues: {
      preferredDate: '',
      preferredTime: '',
    },
  });

  const dates = useMemo(() => slots?.days.map((day) => day.date) ?? [], [slots]);
  const closedDates = useMemo(
    () => slots?.days.filter((day) => day.closed || day.slots.length === 0).map((day) => day.date) ?? [],
    [slots]
  );
  const selectedDate = watch('preferredDate');
  const daySlots = slots?.days.find((day) => day.date === selectedDate)?.slots ?? [];

  // Start on the first bookable slot, and move off a slot that is no longer offered after the slots reload
  useEffect(() => {
    if (!slots) return;
    const current = findSlot(slots, getValues('preferredDate'), getValues('preferredTime'));
    if (current?.status === 'AVAILABLE') return;

    const fallback = findFirstBookableSlot(slots, getValues('preferredDate'));
    setValue('preferredDate', fallback?.date ?? '', { shouldValidate: isSubmitted });
    setValue('preferredTime', fallback?.slot.localTime ?? '', { shouldValidate: isSubmitted });
  }, [slots, getValues, setValue, isSubmitted]);

  const phoneIsVerified = Boolean(verifiedPhone) && watch('prospectPhone') === verifiedPhone;
  const showTimezone = Boolean(slots && !isVisitorTimezone(slots.timezone));

  const onFormSubmit = (data: TourFormData) => {
    const slot = slots && findSlot(slots, data.preferredDate, data.preferredTime);
    if (!slot) return;

    onSubmitLead({
      leadType: 'TOUR_REQUEST',
      prospectName: data.prospectName,
      prospectPhone: data.prospectPhone,
      prospectEmail: data.prospectEmail || undefined,
      preferredSlot: slot.start,
    });
  };

  return (
    <form onSubmit={handleSubmit(onFormSubmit)} className="space-y-4" id="tour-request-form">
      <div>
        <label htmlFor="prospect-name" className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">
          Full Name <span className="text-rose-500 dark:text-rose-400">*</span>
        </label>
        <div className="relative">
          <User className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
          <input
            {...register('prospectName')}
            type="text"
            id="prospect-name"
            placeholder="e.g. Aditi Katiyar"
            className="w-full pl-9 pr-3 py-2.5 rounded-xl glass-input text-xs"
          />
        </div>
        {errors.prospectName && (
          <span className="text-[11px] text-rose-500 dark:text-rose-400 mt-1 block">{errors.prospectName.message}</span>
        )}
      </div>

      <div>
        <label htmlFor="prospect-phone" className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">
          Mobile Number (for OTP Verification) <span className="text-rose-500 dark:text-rose-400">*</span>
        </label>
        <div className="relative">
          <Phone className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
          <input
            {...register('prospectPhone')}
            type="tel"
            id="prospect-phone"
            maxLength={10}
            placeholder="e.g. 9876543210"
            className="w-full pl-9 pr-3 py-2.5 rounded-xl glass-input text-xs"
          />
        </div>
        {errors.prospectPhone ? (
          <span className="text-[11px] text-rose-500 dark:text-rose-400 mt-1 block">{errors.prospectPhone.message}</span>
        ) : (
          phoneIsVerified && (
            <span className="text-[11px] text-emerald-600 dark:text-emerald-400 mt-1 flex items-center gap-1">
              <CheckCircle className="h-3 w-3" /> Phone verified
            </span>
          )
        )}
      </div>

      <div>
        <label htmlFor="prospect-email" className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">
          Email Address (Optional)
        </label>
        <div className="relative">
          <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
          <input
            {...register('prospectEmail')}
            type="email"
            id="prospect-email"
            placeholder="e.g. aditi@example.com"
            className="w-full pl-9 pr-3 py-2.5 rounded-xl glass-input text-xs"
          />
        </div>
        {errors.prospectEmail && (
          <span className="text-[11px] text-rose-500 dark:text-rose-400 mt-1 block">{errors.prospectEmail.message}</span>
        )}
      </div>

      <div>
        <span id="preferred-date-label" className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
          <Calendar className="h-3.5 w-3.5 text-indigo-600 dark:text-indigo-400" />
          Preferred Visit Date <span className="text-rose-500 dark:text-rose-400">*</span>
        </span>
        {slots ? (
          <Controller
            control={control}
            name="preferredDate"
            render={({ field }) => (
              <DateStrip
                id="preferred-slot"
                label="Preferred Visit Date"
                dates={dates}
                closedDates={closedDates}
                value={field.value}
                onChange={(date) => {
                  field.onChange(date);
                  // Keep the chosen time if the new date offers it, otherwise take its first bookable slot
                  const sameTime = findSlot(slots, date, getValues('preferredTime'));
                  if (sameTime?.status !== 'AVAILABLE') {
                    const fallback = findFirstBookableSlot(slots, date);
                    setValue('preferredTime', fallback?.slot.localTime ?? '', { shouldValidate: isSubmitted });
                  }
                }}
              />
            )}
          />
        ) : (
          <div className="flex gap-2 py-1" aria-hidden="true">
            {Array.from({ length: 6 }, (_, i) => (
              <Skeleton key={i} className="shrink-0 w-[4.75rem] h-[4.25rem] rounded-xl" />
            ))}
          </div>
        )}
        {errors.preferredDate && (
          <span className="text-[11px] text-rose-500 dark:text-rose-400 mt-1 block">{errors.preferredDate.message}</span>
        )}
      </div>

      <div>
        <span className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
          <Clock className="h-3.5 w-3.5 text-indigo-600 dark:text-indigo-400" />
          Preferred Time <span className="text-rose-500 dark:text-rose-400">*</span>
        </span>
        {slots ? (
          <Controller
            control={control}
            name="preferredTime"
            render={({ field }) => (
              <TimeSlotPicker
                id="preferred-time"
                label="Preferred Time"
                slots={daySlots}
                value={field.value}
                onChange={field.onChange}
              />
            )}
          />
        ) : (
          <div className="grid grid-cols-3 sm:grid-cols-4 gap-2" aria-hidden="true">
            {Array.from({ length: 8 }, (_, i) => (
              <Skeleton key={i} className="h-8 rounded-lg" />
            ))}
          </div>
        )}
        {errors.preferredTime && (
          <span className="text-[11px] text-rose-500 dark:text-rose-400 mt-1 block">{errors.preferredTime.message}</span>
        )}
        {showTimezone && slots && (
          <span className="text-[11px] text-slate-600 dark:text-slate-400 mt-1.5 flex items-center gap-1">
            <Globe className="h-3 w-3" /> Times are shown in the property&apos;s local time ({formatTimezone(slots.timezone)}).
          </span>
        )}
      </div>

      <button
        type="submit"
        disabled={loading || isLoadingSlots || !slots}
        id="submit-tour-request-btn"
        className="w-full py-3 px-4 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 disabled:opacity-60 text-white font-bold text-sm shadow-lg shadow-indigo-600/30 flex items-center justify-center gap-2 transition-all focus:outline-none focus:ring-2 focus:ring-indigo-500"
      >
        <span>{loading ? 'Processing...' : phoneIsVerified ? 'Submit Tour Request' : 'Continue to OTP Verification'}</span>
        <ArrowRight className="h-4 w-4" />
      </button>
    </form>
  );
}
