import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) =>
  StyleSheet.create({
    createTenantPanel: {
      gap: theme.Spacing.md,
      paddingTop: theme.Spacing.sm,
    },
    createTenantHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: theme.Spacing.md,
      gap: theme.Spacing.sm,
    },
    createTenantBack: {
      padding: theme.Spacing.xs,
      borderRadius: theme.Rounded.default,
      backgroundColor: theme.Colors.primaryContainer,
    },
    createTenantTitle: {
      fontSize: theme.Typography.labelMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
      letterSpacing: 1,
    },
    removeTenantButton: {
      padding: theme.Spacing.xs,
      borderRadius: theme.Rounded.md,
      backgroundColor: theme.Colors.errorContainer,
    },
    inputGroup: {
      gap: theme.Spacing.xs,
    },
    inputLabel: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
      letterSpacing: 1.5,
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.Colors.glassFill,
      borderRadius: theme.Rounded.lg,
      borderWidth: 1,
      borderColor: theme.Colors.glassStroke,
      paddingHorizontal: theme.Spacing.md,
      height: 48,
      gap: theme.Spacing.sm,
    },
    textInput: {
      flex: 1,
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '700',
      color: theme.Colors.onSurface,
      padding: 0,
    },
    statusToggle: {
      paddingVertical: theme.Spacing.sm,
      paddingHorizontal: theme.Spacing.md,
      borderRadius: theme.Rounded.md,
      borderWidth: 1.5,
      borderColor: theme.Colors.glassStroke,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.Colors.glassFill,
    },
    statusToggleText: {
      fontSize: theme.Typography.labelMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
    },
    statusActiveOccupied: {
      backgroundColor: theme.Colors.primary,
      borderColor: theme.Colors.primary,
    },
    statusTextActive: {
      color: theme.Colors.onPrimary,
    },
    errorText: {
      color: theme.Colors.error,
      fontSize: theme.Typography.bodyMedium.fontSize,
      paddingLeft: theme.Spacing.xs,
      marginTop: theme.Spacing.xs,
    },
    errorTextFlat: {
      color: theme.Colors.error,
      fontSize: theme.Typography.bodyMedium.fontSize,
      marginTop: -theme.Spacing.xs,
      marginBottom: theme.Spacing.md,
      paddingLeft: theme.Spacing.xs,
    },
    tenantListContainer: {
      paddingVertical: theme.Spacing.sm,
      paddingHorizontal: theme.Spacing.md,
      backgroundColor: theme.Colors.glassFill,
      borderRadius: theme.Rounded.lg,
      borderColor: theme.Colors.glassStroke,
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    tenantTag: {
      paddingVertical: theme.Spacing.xs,
      paddingHorizontal: theme.Spacing.sm,
      borderRadius: theme.Rounded.default,
      backgroundColor: theme.Colors.primaryContainer,
    },
    tenantTagText: {
      fontSize: theme.Typography.labelMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
    },
    sheetSubtitle: {
      fontSize: theme.Typography.labelSmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontWeight: '700',
    },
    warningContainer: {
      flexDirection: 'row',
      gap: theme.Spacing.sm,
      padding: theme.Spacing.sm,
      borderRadius: theme.Rounded.lg,
      backgroundColor: theme.Colors.errorContainer,
      borderWidth: 1,
      borderColor: theme.Colors.error,
      alignItems: 'flex-start',
    },
    warningText: {
      flex: 1,
      fontSize: theme.Typography.labelMedium.fontSize,
      fontWeight: '700',
      color: theme.Colors.error,
      lineHeight: 18,
    },
    successContainer: {
      flexDirection: 'row',
      gap: theme.Spacing.sm,
      padding: theme.Spacing.sm,
      borderRadius: theme.Rounded.lg,
      backgroundColor: theme.Colors.glassFill,
      borderWidth: 1,
      borderColor: theme.Colors.glassStroke,
      marginTop: theme.Spacing.sm,
      alignItems: 'flex-start',
    },
    suggestionsContainer: {
      maxHeight: 180,
      backgroundColor: theme.Colors.glassFill,
      borderRadius: theme.Rounded.lg,
      borderWidth: 1,
      borderColor: theme.Colors.glassStroke,
      marginTop: theme.Spacing.xs,
      shadowColor: theme.Colors.onSurface,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 3,
    },
    suggestionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: theme.Spacing.sm,
      paddingHorizontal: theme.Spacing.md,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.Colors.outlineVariant,
      gap: theme.Spacing.sm,
    },
    suggestionTextContainer: {
      flex: 1,
    },
    suggestionName: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
    },
    suggestionPhone: {
      fontSize: theme.Typography.labelSmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontWeight: '700',
    },
    quickCreatePrompt: {
      paddingVertical: theme.Spacing.sm,
      paddingHorizontal: theme.Spacing.md,
      backgroundColor: theme.Colors.glassFill,
      borderRadius: theme.Rounded.lg,
      borderWidth: 1,
      borderColor: theme.Colors.glassStroke,
      marginBottom: theme.Spacing.md,
    },
    quickCreatePromptText: {
      fontSize: theme.Typography.labelMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
      flex: 1,
    },
    quickCreateForm: {
      backgroundColor: theme.Colors.glassFill,
      borderRadius: theme.Rounded.xl,
      borderWidth: 1,
      borderColor: theme.Colors.glassStroke,
      padding: theme.Spacing.md,
      gap: theme.Spacing.sm,
      marginBottom: theme.Spacing.md,
    },
    quickCreateTitle: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
      letterSpacing: 1.5,
    },
    quickCreateField: {
      gap: theme.Spacing.xs,
    },
    quickCreateLabel: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
      letterSpacing: 1,
    },
    tenantMatchBox: {
      paddingVertical: theme.Spacing.sm,
      paddingHorizontal: theme.Spacing.md,
      backgroundColor: theme.Colors.glassFill,
      borderRadius: theme.Rounded.lg,
      borderColor: theme.Colors.glassStroke,
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    tenantMatchName: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '700',
      color: theme.Colors.tertiary,
    },
    tenantMatchEmail: {
      fontSize: theme.Typography.labelSmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
    },
  });
