import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    safeArea: {
      flex: 1,
    },
    headerContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 56,
      zIndex: 999,
      borderBottomWidth: 1,
      borderBottomColor: theme.Colors.outlineVariant,
      overflow: 'hidden',
    },
    headerContent: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
    },
    backButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.Colors.surfaceContainerLow,
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
      justifyContent: 'center',
      alignItems: 'center',
    },
    titleWrapper: {
      flex: 1,
      alignItems: 'center',
    },
    compactTitleText: {
      color: theme.Colors.onSurface,
      fontSize: theme.Typography.bodyLarge.fontSize,
      fontWeight: '600',
      letterSpacing: 1,
    },
    mobileScroll: {
      width: '100%',
    },
    desktopScroll: {
      alignItems: 'center',
      width: '100%',
    },
    desktopInner: {
      width: '100%',
      flex: 1,
    },
    titleContainer: {
      marginTop: 16,
      marginBottom: 24,
    },
    titleLineDesktop: {
      ...theme.Typography.headlineLg,
      color: theme.Colors.onSurface,
      lineHeight: 38,
      letterSpacing: -0.5,
    },
    subtitle: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontWeight: '500',
      marginTop: 4,
      lineHeight: 20,
    },
    metricsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      marginBottom: 20,
    },
    metricCard: {
      flex: 1,
      minWidth: 120,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
      backgroundColor: theme.Colors.surfaceContainerLowest,
    },
    metricLabel: {
      fontSize: theme.Typography.bodySmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontWeight: '600',
      marginBottom: 4,
    },
    metricValue: {
      fontSize: theme.Typography.headlineSmall.fontSize,
      fontWeight: '600',
    },
    searchBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.Colors.surfaceContainerLowest,
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
      borderRadius: 12,
      paddingHorizontal: 12,
      height: 44,
      gap: 8,
      marginBottom: 16,
    },
    searchInput: {
      flex: 1,
      color: theme.Colors.onSurface,
      fontSize: theme.Typography.bodyMedium.fontSize,
    },
    filtersContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 12,
      flexWrap: 'wrap',
    },
    filterGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    filterLabelText: {
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '700',
      color: theme.Colors.primary,
      width: 60,
    },
    filterScroll: {
      gap: 8,
    },
    filterPill: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 14,
      backgroundColor: theme.Colors.surfaceContainerLow,
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
    },
    filterPillActive: {
      backgroundColor: theme.Colors.primary,
    },
    filterText: {
      fontSize: theme.Typography.bodySmall.fontSize,
      color: theme.Colors.onSurface,
      fontWeight: '600',
    },
    filterTextActive: {
      color: theme.Colors.surfaceContainerLowest,
    },
    centerContainer: {
      padding: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    errorText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.error,
      textAlign: 'center',
      marginBottom: 16,
    },
    emptyCard: {
      padding: 40,
      borderRadius: 20,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
      backgroundColor: theme.Colors.surfaceContainerLowest,
      marginTop: 20,
    },
    emptyTitle: {
      fontSize: theme.Typography.bodyLg?.fontSize || 18,
      fontWeight: '700',
      color: theme.Colors.onSurface,
      marginTop: 12,
      marginBottom: 6,
    },
    emptySubtitle: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurfaceVariant,
      textAlign: 'center',
      lineHeight: 20,
      maxWidth: 320,
    },
    listContainer: {
      gap: 16,
    },
    mobileCard: {
      padding: 16,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
      backgroundColor: theme.Colors.surfaceContainerLowest,
    },
    cardHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    cardUnitText: {
      fontSize: theme.Typography.bodyLarge.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
    },
    blockBadge: {
      backgroundColor: 'rgba(0, 104, 117, 0.08)',
      paddingVertical: 2,
      paddingHorizontal: 6,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: 'rgba(0, 104, 117, 0.2)',
    },
    blockBadgeText: {
      color: theme.Colors.primary,
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
    },
    cardTitleText: {
      fontSize: theme.Typography.bodyLarge.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
      marginBottom: 6,
    },
    cardDescText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurfaceVariant,
      lineHeight: 18,
      marginBottom: 10,
    },
    cardFooterRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 4,
    },
    cardDateText: {
      fontSize: theme.Typography.bodySmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
    },
    pill: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    pillText: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
    },
    filterButton: {
      backgroundColor: theme.Colors.primary,
      borderRadius: 10,
      paddingHorizontal: 16,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    filterButtonText: {
      color: theme.Colors.surfaceContainerLowest,
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '700',
    },
    paginationRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 20,
      marginTop: 24,
      marginBottom: 20,
    },
    pageButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.Colors.surfaceContainerLow,
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
      justifyContent: 'center',
      alignItems: 'center',
    },
    pageButtonDisabled: {
      backgroundColor: theme.Colors.surfaceContainerLowest,
      borderColor: theme.Colors.outlineVariant,
      opacity: 0.5,
    },
    pageText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '700',
      color: theme.Colors.onSurface,
    },
  });
