import { StyleSheet } from 'react-native';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  gradient: { flex: 1, backgroundColor: theme.Colors.background },
  safeArea: { flex: 1 },
  headerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 56,
    zIndex: 999,
    borderBottomWidth: 1.5,
    borderBottomColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  headerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.Spacing.md,
  },
  titleWrapper: {
    flex: 1,
    alignItems: 'center',
  },
  backButton: {
    width: 44, 
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: theme.Colors.glassFill,
    justifyContent: 'center', 
    alignItems: 'center',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  headerTitle: { fontSize: theme.Typography.bodyLg.fontSize, fontWeight: '600', color: theme.Colors.onSurface },
  headerSubtitle: { fontSize: theme.Typography.bodySmall.fontSize, color: theme.Colors.onSurfaceVariant, fontWeight: '500', marginTop: 2 },
  
  headerSaveBtnWrapper: {
    borderRadius: 22,
    overflow: 'hidden',
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 2,
    marginLeft: 12,
  },
  headerSaveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.Spacing.xs,
    height: 44,
    borderRadius: 22,
    paddingHorizontal: theme.Spacing.md,
  },
  headerSaveText: {
    color: theme.Colors.surfaceContainerLowest,
    fontWeight: '600',
    fontSize: theme.Typography.bodySmall.fontSize,
    letterSpacing: 0.5,
  },
  floatingSaveBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: theme.Spacing.lg,
    paddingVertical: theme.Spacing.md,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderTopColor: theme.Colors.outline,
    backgroundColor: theme.Colors.surfaceContainerLowest,
  },
  floatingSaveBtn: {
    borderRadius: 26,
    overflow: 'hidden',
  },
  floatingSaveBtnInner: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderRadius: 26,
    backgroundColor: theme.Colors.primary,
  },
  floatingSaveText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '600',
    letterSpacing: 1,
  },

  filterSection: { paddingHorizontal: theme.Spacing.lg, marginBottom: 20 },
  
  desktopMonthSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.Colors.surfaceContainerLow,
    borderRadius: 12,
    height: 48,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
  },
  monthSelector: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    backgroundColor: theme.Colors.surfaceContainerLow,
    borderRadius: 12, 
    paddingVertical: theme.Spacing.sm,
    borderWidth: 1,
    borderColor: theme.Colors.outline,
    marginTop: theme.Spacing.md,
  },
  monthBtn: {
    minWidth: 44,
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.Spacing.sm,
  },
  monthText: { flex: 1, textAlign: 'center', fontSize: theme.Typography.bodyLarge.fontSize, fontWeight: '600', color: theme.Colors.primary },
  
  listContent: { paddingHorizontal: theme.Spacing.lg, paddingBottom: 40 },
  emptyState: { padding: 40, alignItems: 'center' },
  emptyText: { color: theme.Colors.onSurfaceVariant, fontSize: theme.Typography.bodyLarge.fontSize },
  
  floorCard: {
    marginBottom: theme.Spacing.lg,
    borderRadius: 16,
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderWidth: 1, 
    borderColor: theme.Colors.outline,
    paddingHorizontal: theme.Spacing.lg,
    overflow: 'hidden',
  },
  floorHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 20 },
  floorHeaderText: { fontSize: theme.Typography.bodyLg.fontSize, fontWeight: '600', color: theme.Colors.primary },
  
  rowCard: {
    flexDirection: 'row', alignItems: 'center',
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: isDark ? 'rgba(255, 255, 255, 0.06)' : 'rgba(0, 104, 117, 0.1)',
  },
  rowError: { backgroundColor: isDark ? 'rgba(255, 107, 107, 0.12)' : 'rgba(254, 226, 226, 0.4)', borderRadius: 12, paddingHorizontal: theme.Spacing.sm },
  
  rowLeft: { flex: 2 },
  unitName: { fontSize: theme.Typography.bodyLarge.fontSize, fontWeight: '600', color: theme.Colors.onSurface },
  tenantName: { fontSize: theme.Typography.bodyMedium.fontSize, color: theme.Colors.onSurfaceVariant, marginVertical: 2 },
  prevReading: { fontSize: theme.Typography.labelSmall.fontSize, color: theme.Colors.onSurfaceVariant, fontWeight: '600' },
  
  rowMiddle: { flex: 1.5, alignItems: 'flex-end', paddingRight: 12 },
  consumedText: { fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '600', color: theme.Colors.primary },
  costText: { fontSize: theme.Typography.labelSmall.fontSize, color: theme.Colors.primary, fontWeight: '600', marginTop: 2 },
  
  rowRight: { flex: 2, alignItems: 'flex-end' },
  input: {
    backgroundColor: theme.Colors.surfaceContainerLowest, 
    borderRadius: 10,
    borderWidth: 1, 
    borderColor: isDark ? 'rgba(255, 255, 255, 0.15)' : 'rgba(0, 104, 117, 0.15)',
    width: '100%', 
    paddingVertical: 10, 
    paddingHorizontal: 12,
    fontSize: theme.Typography.bodyLarge.fontSize, 
    fontWeight: '600', 
    color: theme.Colors.onSurface, 
    textAlign: 'right',
  },
  inputError: { borderColor: theme.Colors.error, color: theme.Colors.error },
  errorText: { fontSize: theme.Typography.labelSmall.fontSize, color: theme.Colors.error, fontWeight: '600', marginTop: theme.Spacing.xs },

  // Desktop specific styles
  desktopShell: {
    flex: 1,
    flexDirection: 'row',
  },
  desktopMain: {
    flex: 1,
    height: '100%',
  },
  topbar: {
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: theme.Spacing.xl,
    borderBottomWidth: 1,
    borderColor: theme.Colors.glassStroke,
    backgroundColor: theme.Colors.glassFill,
  },
  topbarTabs: {
    flexDirection: 'row',
    gap: theme.Spacing.xl,
  },
  topbarTab: {
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
  },
  topbarTabActive: {
    color: theme.Colors.primary,
    fontWeight: '600',
  },
  topbarRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  backButtonDesktop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
    paddingHorizontal: theme.Spacing.md,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
  },
  backButtonTextDesktop: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurface,
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: theme.Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: theme.Colors.surfaceContainerLowest,
    fontWeight: '700',
    fontSize: theme.Typography.bodyMedium.fontSize,
  },
  desktopContent: {
    paddingBottom: 80,
  },
  desktopInner: {
    width: '100%',
    maxWidth: 1200,
    alignSelf: 'center',
    paddingHorizontal: theme.Spacing.lg,
    paddingTop: theme.Spacing.xl,
  },
  desktopHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.Spacing.xl,
  },
  largeTitleContainer: {
    flex: 1,
  },
  titleLineDesktop: {
    ...theme.Typography.headlineLg,
    color: theme.Colors.onSurface,
  },
  desktopSubtitle: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '500',
    marginTop: theme.Spacing.xs,
  },
  desktopSaveButtonWrapper: {
    borderRadius: 12,
  },
  desktopSaveButton: {
    height: 44,
    paddingHorizontal: theme.Spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.Spacing.sm,
    backgroundColor: theme.Colors.primary,
    borderRadius: 10,
  },
  desktopSaveButtonText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  desktopFilterRow: {
    flexDirection: 'row',
    gap: theme.Spacing.lg,
    alignItems: 'flex-end',
    marginBottom: theme.Spacing.xl,
    zIndex: 1000,
  },
  filterLabelCaps: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 0.2,
    marginBottom: 6,
  },
  emptyStateCard: {
    backgroundColor: theme.Colors.surfaceContainerLowest,
    borderRadius: 16,
    padding: theme.Spacing.xxl,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.Colors.outline,
  },
  desktopGrid: {
    flexDirection: 'row',
    gap: theme.Spacing.lg,
  },
  desktopLeftColumn: {
    flex: 1.6,
    gap: theme.Spacing.lg,
  },
  desktopRightColumn: {
    flex: 1,
  },
  summaryCard: {
    backgroundColor: theme.Colors.glassFill,
    borderRadius: 24,
    padding: theme.Spacing.lg,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    shadowColor: theme.Colors.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 30,
    elevation: 3,
    position: 'sticky',
    top: 24,
  },
  summaryCardTitle: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
    letterSpacing: 1.5,
    marginBottom: 20,
  },
  summaryMetricsGrid: {
    flexDirection: 'row',
    gap: theme.Spacing.md,
    marginBottom: theme.Spacing.md,
  },
  summaryMetricItem: {
    flex: 1,
    backgroundColor: isDark ? 'rgba(15, 23, 32, 0.65)' : 'rgba(255, 255, 255, 0.6)',
    padding: theme.Spacing.md,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
  },
  summaryMetricLabel: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 0.5,
    marginBottom: theme.Spacing.xs,
  },
  summaryMetricValue: {
    fontSize: theme.Typography.titleLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  previewDivider: {
    height: 1,
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.08)' : 'rgba(0, 104, 117, 0.1)',
    marginVertical: theme.Spacing.md,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 6,
  },
  summaryLabel: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '500',
  },
  summaryValue: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurface,
    fontWeight: '700',
  },
  warningAlertBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
    backgroundColor: theme.Colors.tertiaryContainer,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.Colors.tertiaryContainer,
    marginTop: 20,
  },
  warningAlertText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.tertiary,
    fontWeight: '600',
    flex: 1,
  },
  paginationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: theme.Spacing.md,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: isDark ? 'rgba(255, 255, 255, 0.08)' : 'rgba(0, 104, 117, 0.1)',
  },
  pageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.xs,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
  },
  pageButtonDisabled: {
    opacity: 0.4,
  },
  pageButtonText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  pageButtonTextDisabled: {
    color: theme.Colors.onSurfaceVariant,
  },
  pageInfoText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '600',
    color: theme.Colors.onBackground,
  },
  listControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.Spacing.md,
    gap: 12,
  },
  listControlsRowMobile: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.Spacing.md,
    paddingHorizontal: theme.Spacing.lg,
    gap: 12,
  },
  controlLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.xs,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: isDark ? 'rgba(0, 229, 255, 0.1)' : 'rgba(0, 104, 117, 0.05)',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(0, 229, 255, 0.2)' : 'rgba(0, 104, 117, 0.1)',
  },
  controlLinkText: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
    letterSpacing: 0.5,
  },
  controlSeparator: {
    width: 1,
    height: 12,
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.15)' : 'rgba(0, 104, 117, 0.15)',
  },
});
