import { StyleSheet } from 'react-native';
import { Theme } from '@/src/theme/Theme';

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  headerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 999,
    borderBottomWidth: 1.5,
    borderBottomColor: theme.Colors.glassFill,
    overflow: 'hidden',
  },
  headerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.Spacing.md,
  },
  titleWrapper: {
    flex: 1,
    alignItems: 'center',
  },
  compactTitleText: {
    fontSize: theme.Typography.bodyLg.fontSize,
    fontWeight: '600',
    color: theme.Colors.onSurface,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: theme.Colors.glassFill,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerGradientTouch: {
    borderRadius: 100,
    overflow: 'hidden',
  },
  headerGradientInner: {
    paddingVertical: 7,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.xs,
    borderRadius: 100,
  },
  headerGradientText: {
    color: theme.Colors.surfaceContainerLowest,
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  desktopScroll: { paddingHorizontal: 40, alignItems: 'center' },
  mobileScroll: { paddingHorizontal: 20 },
  inner: { width: '100%', maxWidth: 1080 },
  selectorContainer: { flexDirection: 'row', alignItems: 'center', gap: theme.Spacing.sm },
  arrowBadge: {
    width: 44,
    height: 44,
    backgroundColor: theme.Colors.glassFill,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    justifyContent: 'center',
    alignItems: 'center',
  },
  monthBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    backgroundColor: theme.Colors.glassFill,
    paddingHorizontal: 16,
    borderRadius: 22,
    gap: 8,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
  },
  monthBadgeText: { fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '600', color: theme.Colors.primary },
  
  resultsContainer: { width: '100%', gap: theme.Spacing.md, marginTop: 10 },
  summaryCard: { padding: theme.Spacing.lg, backgroundColor: theme.Colors.glassFill, borderWidth: 1.5, borderColor: theme.Colors.glassStroke, borderRadius: 24 },
  summaryLabel: { fontSize: theme.Typography.labelSmall.fontSize, fontWeight: '600', color: theme.Colors.primary, letterSpacing: 0.2, marginBottom: theme.Spacing.xs },
  summaryAmount: { fontSize: theme.Typography.headlineLg.fontSize, fontWeight: '600', color: theme.Colors.onSurface, marginBottom: 20 },
  summaryStatusRow: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.Spacing.md, width: '100%' },
  miniStat: { flex: 1, minWidth: '47%', backgroundColor: theme.Colors.surfaceContainerLow, borderWidth: 1, borderColor: theme.Colors.outlineVariant },
  actionGroup: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 20 },
  publishBtn: { flex: 1, minWidth: 140 },
  reGenerateBtn: { flex: 1, minWidth: 140 },
  
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.Colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: theme.Colors.outlineVariant,
    borderRadius: 16,
    paddingHorizontal: theme.Spacing.md,
    paddingVertical: 12,
    gap: 10,
  },
  searchInput: { flex: 1, color: theme.Colors.onSurface, fontSize: theme.Typography.bodyMedium.fontSize, fontWeight: '600' },
  
  paginationBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: theme.Spacing.sm,
    paddingVertical: 12,
  },
  paginationInfo: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
  },
  paginationActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
  },
  pageIndicator: {
    paddingHorizontal: 12,
  },
  pageIndicatorText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  pageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    borderRadius: 22,
    minHeight: 44,
    paddingHorizontal: 16,
    gap: theme.Spacing.xs,
  },
  pageBtnDisabled: {
    opacity: 0.5,
  },
  pageBtnText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
  },
  pageBtnTextDisabled: {
    color: theme.Colors.onSurfaceVariant,
  },
});
