import { StyleSheet } from 'react-native';
import { SerifHeadlineFont } from '@/src/theme/Theme';

const CELL_SIZE = 60;

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: isDark ? 'rgba(0, 0, 0, 0.72)' : 'rgba(0, 0, 0, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 440,
    height: '92%',
    maxHeight: 780,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.14)' : 'rgba(255, 255, 255, 0.85)',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: isDark ? 0.6 : 0.25,
    shadowRadius: 30,
    elevation: 16,
  },
  dragHandleContainer: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 4,
  },
  dragHandle: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.22)' : 'rgba(0, 0, 0, 0.15)',
  },
  mobilePopupHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: theme.Spacing.lg,
    paddingTop: theme.Spacing.xs,
    paddingBottom: theme.Spacing.sm,
  },
  mobileTitleBlock: {
    flex: 1,
    paddingRight: theme.Spacing.sm,
  },
  mobileKicker: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: theme.Colors.primary,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  mobileTitleText: {
    fontFamily: SerifHeadlineFont,
    fontSize: 20,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    letterSpacing: -0.3,
    lineHeight: 26,
  },
  mobileCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.08)' : 'rgba(0, 0, 0, 0.05)',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.12)' : 'rgba(0, 0, 0, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  mobileBottomActionContainer: {
    paddingHorizontal: theme.Spacing.lg,
    paddingBottom: theme.Spacing.lg,
    paddingTop: theme.Spacing.xs,
  },
  modalContentDesktop: {
    width: '85%',
    maxWidth: 1300,
    height: '85%',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.12)' : 'rgba(255, 255, 255, 0.8)',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 25,
    elevation: 10,
  },
  desktopShell: {
    flex: 1,
  },
  desktopMain: {
    flex: 1,
    padding: theme.Spacing.xl,
    gap: 20,
  },
  desktopHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  largeTitleContainer: {
    flex: 1,
  },
  titleLineDesktop: {
    fontFamily: SerifHeadlineFont,
    fontSize: theme.Typography.headlineMd.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    letterSpacing: -0.5,
  },
  backButtonDesktop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.Spacing.sm,
    paddingHorizontal: theme.Spacing.md,
    paddingVertical: 10,
    borderRadius: 100,
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
  },
  backButtonTextDesktop: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurface,
  },
  desktopMainContent: {
    flex: 1,
    flexDirection: 'row',
    gap: theme.Spacing.lg,
  },
  desktopCanvasColumn: {
    flex: 1.5,
    height: '100%',
  },
  desktopGridWrapper: {
    flex: 1,
    backgroundColor: isDark ? 'rgba(15, 23, 32, 0.65)' : theme.Colors.glassFill,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.10)' : theme.Colors.glassStroke,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  desktopSidebarColumn: {
    width: 420,
    height: '100%',
  },
  desktopCard: {
    borderRadius: 24,
    padding: theme.Spacing.lg,
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.10)' : theme.Colors.glassStroke,
    backgroundColor: isDark ? 'rgba(15, 23, 32, 0.65)' : theme.Colors.glassFill,
    overflow: 'hidden',
  },
  safeArea: {
    flex: 1,
  },
  header: {
    paddingHorizontal: theme.Spacing.lg,
    paddingVertical: theme.Spacing.md,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleContainer: {
    marginTop: theme.Spacing.md,
  },
  titleLine: {
    fontFamily: SerifHeadlineFont,
    fontSize: theme.Typography.headlineXl.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    lineHeight: 46,
    letterSpacing: -1,
  },
  gridWrapper: {
    flex: 1,
    backgroundColor: theme.Colors.glassFill,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.Colors.glassStroke,
    overflow: 'hidden',
    marginBottom: 20,
    marginHorizontal: theme.Spacing.lg,
  },
  canvasContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.Colors.glassFill,
  },
  loadingText: {
    marginTop: 12,
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '600',
    color: theme.Colors.primary,
    letterSpacing: 0.5,
  },
  isometricContainer: {
    padding: 40,
  },
  gridContainer: {
    backgroundColor: 'rgba(0, 104, 117, 0.02)',
    borderWidth: 2,
    borderColor: 'rgba(0, 104, 117, 0.1)',
  },
  gridRow: {
    flexDirection: 'row',
  },
  cell: {
    width: CELL_SIZE,
    height: CELL_SIZE,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderColor: 'rgba(0, 104, 117, 0.15)',
  },
  cellEmpty: {
    backgroundColor: 'transparent',
  },
  cellActive: {
    borderColor: theme.Colors.primary,
    backgroundColor: theme.Colors.primary,
    borderWidth: 2,
    shadowColor: 'black',
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cellText: {
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '800',
    color: theme.Colors.surfaceContainerLowest,
  },
  detailSheetWrapper: {
    position: 'absolute',
    bottom: 80,
    left: 0,
    right: 0,
    zIndex: 1000,
    paddingHorizontal: 20,
  },
  detailSheet: {
    borderRadius: 32,
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
    padding: theme.Spacing.lg,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    overflow: 'hidden',
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sheetUnitTitle: {
    fontSize: theme.Typography.headlineSmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  sheetSubtitle: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  closeButtonSmall: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sheetContent: {
    gap: theme.Spacing.md,
  },
  inputGroup: {
    gap: theme.Spacing.sm,
  },
  inputLabel: {
    fontSize: theme.Typography.labelSmall.fontSize,
    fontWeight: '800',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 1,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    borderRadius: 16,
    paddingHorizontal: theme.Spacing.md,
    paddingVertical: 12,
    gap: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
  },
  textInput: {
    flex: 1,
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.onSurface,
    fontWeight: '600',
    paddingVertical: theme.Spacing.xs,
  },
  tenantListContainer: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    borderRadius: 16,
    borderColor: 'rgba(255, 255, 255, 0.55)',
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tenantList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.Spacing.sm,
    marginBottom: theme.Spacing.xs,
  },
  tenantTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    gap: 6,
  },
  tenantTagText: {
    fontSize: theme.Typography.bodySmall.fontSize,
    fontWeight: '700',
    color: theme.Colors.primary,
  },
  removeBtn: {
    padding: 6,
    borderRadius: 10,
    backgroundColor: 'rgba(229, 57, 53, 0.1)',
  },
  statusContainer: {
    flexDirection: 'row',
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.04)',
    borderRadius: 14,
    padding: 4,
    gap: 6,
    marginTop: theme.Spacing.md,
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.08)' : theme.Colors.outlineVariant,
  },
  statusToggle: {
    flex: 1,
    height: 40,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  statusToggleText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: theme.Colors.onSurfaceVariant,
    fontFamily: 'Inter',
  },
  statusActiveVacant: {
    backgroundColor: isDark ? 'rgba(0, 229, 255, 0.14)' : 'rgba(0, 104, 117, 0.10)',
    borderColor: isDark ? 'rgba(0, 229, 255, 0.35)' : 'rgba(0, 104, 117, 0.25)',
  },
  statusTextVacant: {
    color: isDark ? '#00E5FF' : '#006875',
    fontWeight: '800',
    fontFamily: 'Inter',
  },
  statusActiveOccupied: {
    backgroundColor: isDark ? 'rgba(255, 107, 107, 0.14)' : 'rgba(186, 26, 26, 0.10)',
    borderColor: isDark ? 'rgba(255, 107, 107, 0.35)' : 'rgba(186, 26, 26, 0.25)',
  },
  statusTextOccupied: {
    color: isDark ? '#FF6B6B' : '#ba1a1a',
    fontWeight: '800',
    fontFamily: 'Inter',
  },
  statusTextActive: {
    color: theme.Colors.primary,
  },
  saveButton: {
    height: 56,
    borderRadius: 28,
    shadowColor: theme.Colors.secondary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  saveButtonGradient: {
    flex: 1,
    height: '100%',
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButtonText: {
    fontSize: theme.Typography.bodyLarge.fontSize,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: 0.5,
  },
  warningContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(229, 57, 53, 0.08)',
    borderColor: 'rgba(229, 57, 53, 0.15)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    gap: 10,
    marginBottom: theme.Spacing.sm,
  },
  warningText: {
    flex: 1,
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.error,
    fontWeight: '600',
    lineHeight: 16,
  },
  suggestionsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 104, 117, 0.15)',
    marginTop: theme.Spacing.sm,
    maxHeight: 200,
    overflow: 'hidden',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
    zIndex: 9999,
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: theme.Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
    gap: 12,
  },
  suggestionTextContainer: {
    flex: 1,
  },
  suggestionName: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '700',
    color: theme.Colors.onSurface,
  },
  suggestionPhone: {
    fontSize: theme.Typography.bodySmall.fontSize,
    color: theme.Colors.onSurfaceVariant,
    marginTop: 2,
  },
  quickCreatePrompt: {
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 104, 117, 0.15)',
    padding: 14,
    marginBottom: 12,
  },
  quickCreatePromptText: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    color: theme.Colors.primary,
    fontWeight: '700',
    flex: 1,
  },
  searchResultContainer: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(46, 125, 50, 0.05)',
    borderRadius: 16,
    borderColor: 'rgba(46, 125, 50, 0.15)',
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  createTenantPanel: {
    gap: theme.Spacing.md,
  },
  createTenantHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: theme.Spacing.sm,
    paddingBottom: theme.Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 104, 117, 0.1)',
  },
  createTenantBack: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(0, 104, 117, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  createTenantTitle: {
    fontSize: theme.Typography.bodyMedium.fontSize,
    fontWeight: '800',
    color: theme.Colors.primary,
    letterSpacing: 1,
  },
  // Creative Floor Tabs & Controls
  floorTabsScroll: {
    flexGrow: 0,
    marginVertical: 4,
  },
  floorTabsRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  floorTabPill: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 100,
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.07)' : 'rgba(0, 0, 0, 0.05)',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.12)' : 'rgba(0, 0, 0, 0.08)',
  },
  floorTabPillActive: {
    backgroundColor: theme.Colors.primary,
    borderColor: theme.Colors.primary,
    shadowColor: theme.Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 3,
  },
  floorTabText: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
  },
  floorTabTextActive: {
    color: '#ffffff',
    fontWeight: '800',
  },
  // Floating Canvas Controls Bar
  canvasFloatingToolbar: {
    position: 'absolute',
    bottom: 14,
    left: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: isDark ? 'rgba(15, 23, 32, 0.88)' : 'rgba(255, 255, 255, 0.92)',
    borderRadius: 14,
    padding: 5,
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.12)' : 'rgba(0, 0, 0, 0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
    zIndex: 100,
  },
  toolbarButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.06)' : 'rgba(0, 0, 0, 0.04)',
  },
  toolbarButtonActive: {
    backgroundColor: theme.Colors.primary,
  },
  toolbarButtonText: {
    fontSize: 11,
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  toolbarButtonTextActive: {
    color: '#ffffff',
  },
  toolbarDivider: {
    width: 1,
    height: 18,
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.15)' : 'rgba(0, 0, 0, 0.1)',
    marginHorizontal: 2,
  },
  // Canvas Legend Overlay
  canvasLegendOverlay: {
    position: 'absolute',
    top: 14,
    right: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: isDark ? 'rgba(15, 23, 32, 0.88)' : 'rgba(255, 255, 255, 0.92)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.12)' : 'rgba(0, 0, 0, 0.08)',
    zIndex: 100,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  legendDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  legendText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.Colors.onSurface,
  },
  // Right Column Floor Directory
  directoryContainer: {
    flex: 1,
    gap: 12,
  },
  directoryHeroCard: {
    borderRadius: 20,
    padding: 16,
    backgroundColor: isDark ? 'rgba(15, 23, 32, 0.75)' : theme.Colors.glassFill,
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.12)' : theme.Colors.glassStroke,
    gap: 10,
  },
  directoryHeroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  directoryKicker: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: theme.Colors.primary,
    textTransform: 'uppercase',
  },
  directoryTitle: {
    fontFamily: SerifHeadlineFont,
    fontSize: 18,
    fontWeight: '800',
    color: theme.Colors.onSurface,
    letterSpacing: -0.3,
  },
  directoryMetricsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  directoryMetricChip: {
    flex: 1,
    padding: 10,
    borderRadius: 14,
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.03)',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.08)' : 'rgba(0, 0, 0, 0.05)',
  },
  directoryMetricLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.Colors.onSurfaceVariant,
    textTransform: 'uppercase',
  },
  directoryMetricValue: {
    fontSize: 15,
    fontWeight: '900',
    color: theme.Colors.onSurface,
    marginTop: 2,
  },
  unitListWrapper: {
    flex: 1,
  },
  unitListTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: theme.Colors.onSurfaceVariant,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  unitListItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 16,
    backgroundColor: isDark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(255, 255, 255, 0.8)',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.06)',
    marginBottom: 8,
  },
  unitListItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  unitBadgeSmall: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unitBadgeSmallText: {
    fontSize: 14,
    fontWeight: '900',
    color: '#ffffff',
  },
  unitListItemInfo: {
    flex: 1,
    gap: 2,
  },
  unitListItemTenant: {
    fontSize: 13,
    fontWeight: '800',
    color: theme.Colors.onSurface,
  },
  unitListItemSub: {
    fontSize: 11,
    color: theme.Colors.onSurfaceVariant,
    fontWeight: '600',
  },
  unitInspectAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.Colors.primaryContainer,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  unitInspectText: {
    fontSize: 11,
    fontWeight: '800',
    color: theme.Colors.primary,
  },
});
