import { StyleSheet } from 'react-native';
import { withAlpha } from '@/src/theme/colorUtils';

export const createStyles = (theme: any, isDark: boolean = false) =>
  StyleSheet.create({
    desktopCard: {
      borderRadius: theme.Rounded.xl,
      backgroundColor: theme.Colors.surfaceContainerLowest,
      borderWidth: 1,
      borderColor: theme.Colors.outline,
      overflow: 'hidden',
    },
    sheetHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: theme.Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? withAlpha(theme.Colors.onSurface, 0.08) : withAlpha(theme.Colors.onSurface, 0.05),
    },
    sheetUnitTitle: {
      fontSize: theme.Typography.headlineSmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
    },
    sheetSubtitle: {
      fontSize: theme.Typography.bodySmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      fontWeight: '600',
      marginTop: 2,
    },
    closeButtonSmall: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: isDark ? withAlpha(theme.Colors.onSurface, 0.08) : withAlpha(theme.Colors.onSurface, 0.03),
      justifyContent: 'center',
      alignItems: 'center',
    },
    sheetContent: {
      padding: 20,
    },
    createTenantPanel: {
      gap: 12,
    },
    createTenantHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.Spacing.sm,
      marginBottom: theme.Spacing.sm,
    },
    createTenantBack: {
      padding: theme.Spacing.xs,
    },
    createTenantTitle: {
      fontSize: theme.Typography.labelLarge?.fontSize || 14,
      fontWeight: '600',
      color: theme.Colors.primary,
      letterSpacing: 0.5,
    },
    inputGroup: {
      gap: 6,
    },
    inputLabel: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurfaceVariant,
      letterSpacing: 0.5,
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? theme.Colors.surfaceContainerLowest : theme.Colors.surfaceContainerLow,
      borderWidth: 1,
      borderColor: isDark ? withAlpha(theme.Colors.onSurface, 0.12) : theme.Colors.outlineVariant,
      borderRadius: 12,
      paddingHorizontal: 12,
      height: 48,
      gap: theme.Spacing.sm,
    },
    textInput: {
      flex: 1,
      color: theme.Colors.onSurface,
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '600',
    },
    statusContainer: {
      flexDirection: 'row',
      backgroundColor: isDark ? withAlpha(theme.Colors.onSurface, 0.05) : withAlpha(theme.Colors.onSurface, 0.04),
      borderRadius: 14,
      padding: 4,
      gap: 6,
      marginTop: theme.Spacing.md,
      borderWidth: 1,
      borderColor: isDark ? withAlpha(theme.Colors.onSurface, 0.08) : theme.Colors.outlineVariant,
    },
    statusToggle: {
      flex: 1,
      height: 40,
      borderRadius: 10,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: 'transparent',
      backgroundColor: 'transparent',
    },
    statusToggleText: {
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '600',
      letterSpacing: 0.2,
      color: theme.Colors.onSurfaceVariant,
    },
    statusActiveVacant: {
      backgroundColor: isDark ? withAlpha(theme.Colors.primary, 0.14) : withAlpha(theme.Colors.primary, 0.1),
      borderColor: isDark ? withAlpha(theme.Colors.primary, 0.35) : withAlpha(theme.Colors.primary, 0.25),
    },
    statusTextVacant: {
      color: isDark ? theme.Colors.primary : theme.Colors.primary,
      fontWeight: '600',
    },
    statusDotVacant: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: isDark ? theme.Colors.primary : theme.Colors.primary,
    },
    statusActiveOccupied: {
      backgroundColor: isDark ? withAlpha(theme.Colors.error, 0.14) : withAlpha(theme.Colors.error, 0.1),
      borderColor: isDark ? withAlpha(theme.Colors.error, 0.35) : withAlpha(theme.Colors.error, 0.25),
    },
    statusTextOccupied: {
      color: isDark ? theme.Colors.error : theme.Colors.error,
      fontWeight: '600',
    },
    statusDotOccupied: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: isDark ? theme.Colors.error : theme.Colors.error,
    },
    statusDisabled: {
      opacity: 0.5,
    },
    statusLockedHint: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 6,
      paddingHorizontal: 4,
    },
    statusLockedText: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurfaceVariant,
    },
    cancelTenantBtn: {
      flex: 1,
      height: 44,
      borderRadius: 12,
      backgroundColor: isDark ? withAlpha(theme.Colors.onSurface, 0.06) : withAlpha(theme.Colors.onSurface, 0.04),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isDark ? withAlpha(theme.Colors.onSurface, 0.12) : theme.Colors.outlineVariant,
    },
    cancelTenantBtnText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '700',
      color: theme.Colors.onSurfaceVariant,
    },
    createAssignBtn: {
      flex: 1,
      height: 44,
      borderRadius: 12,
      backgroundColor: theme.Colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    createAssignBtnText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.onPrimary,
      letterSpacing: 0.5,
    },
    statusTextActive: {
      color: theme.Colors.primary,
    },
    tenantListContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? withAlpha(theme.Colors.onSurface, 0.05) : withAlpha(theme.Colors.onSurface, 0.02),
      padding: 10,
      borderRadius: 12,
    },
    tenantTag: {
      backgroundColor: isDark ? withAlpha(theme.Colors.primary, 0.15) : withAlpha(theme.Colors.primary, 0.08),
      paddingHorizontal: theme.Spacing.sm,
      paddingVertical: theme.Spacing.xs,
      borderRadius: 6,
    },
    tenantTagText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '700',
      color: theme.Colors.primary,
    },
    removeBtn: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: withAlpha(theme.Colors.error, 0.1),
      justifyContent: 'center',
      alignItems: 'center',
    },
    warningContainer: {
      flexDirection: 'row',
      backgroundColor: withAlpha(theme.Colors.error, 0.06),
      borderWidth: 1,
      borderColor: withAlpha(theme.Colors.error, 0.12),
      padding: 12,
      borderRadius: 12,
      gap: theme.Spacing.sm,
    },
    warningText: {
      flex: 1,
      fontSize: theme.Typography.bodySmall.fontSize,
      color: theme.Colors.error,
      fontWeight: '600',
      lineHeight: 16,
    },
    suggestionsContainer: {
      maxHeight: 160,
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
      borderRadius: 12,
      backgroundColor: theme.Colors.surfaceContainerLowest,
      marginTop: theme.Spacing.xs,
    },
    suggestionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 12,
      gap: theme.Spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: withAlpha(theme.Colors.onSurface, 0.03),
    },
    suggestionTextContainer: {
      flex: 1,
    },
    suggestionName: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '700',
      color: theme.Colors.onSurface,
    },
    suggestionPhone: {
      fontSize: theme.Typography.labelSmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      marginTop: 2,
    },
    quickCreatePrompt: {
      padding: 12,
      backgroundColor: withAlpha(theme.Colors.primary, 0.04),
      borderWidth: 1,
      borderColor: withAlpha(theme.Colors.primary, 0.1),
      borderRadius: 12,
      marginTop: theme.Spacing.xs,
    },
    quickCreatePromptText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '700',
      color: theme.Colors.primary,
      flex: 1,
    },
    searchResultContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: withAlpha(theme.Colors.primary, 0.04),
      padding: 12,
      borderRadius: 12,
    },
    saveButton: {
      borderRadius: theme.Rounded.md,
      backgroundColor: theme.Colors.primary,
      height: 48,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: theme.Spacing.sm,
    },
    saveButtonGradient: {
      height: 48,
      justifyContent: 'center',
      alignItems: 'center',
    },
    saveButtonText: {
      color: theme.Colors.onPrimary,
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '700',
    },
  });
