import { Platform, StyleSheet } from 'react-native';
import { Theme } from '@/src/theme/Theme';

export const createStyles = (theme: any, isDark: boolean) =>
  StyleSheet.create({
    container: {
      gap: 16,
    },
    containerDesktop: {
      paddingTop: 24,
    },
    heroSection: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 16,
      marginBottom: 24,
    },
    heroTitle: {
      ...theme.Typography.headlineLg,
      color: theme.Colors.onSurface,
      letterSpacing: -0.5,
    },
    heroSubtitle: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurfaceVariant,
      marginTop: 4,
      maxWidth: 600,
    },
    heroActions: {
      flexDirection: 'row',
      gap: 10,
    },
    actionPillBtn: {
      borderRadius: 100,
      overflow: 'hidden',
    },
    actionPillGradient: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 20,
      paddingVertical: 12,
      backgroundColor: theme.Colors.primary,
      borderRadius: 100,
    },
    actionPillText: {
      color: theme.Colors.surfaceContainerLowest,
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '600',
      letterSpacing: 0.8,
    },
    hubGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 16,
      marginBottom: 28,
    },
    hubCardTouch: {
      flex: 1,
      minWidth: 240,
    },
    hubCard: {
      padding: 20,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: theme.Colors.glassStroke,
      backgroundColor: theme.Colors.glassFill,
    },
    hubCardActive: {
      borderColor: theme.Colors.primary,
      backgroundColor: 'rgba(0, 104, 117, 0.08)',
    },
    hubCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 14,
    },
    hubIconHalo: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    hubBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      backgroundColor: theme.Colors.surfaceContainerLowest,
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
    },
    hubBadgeText: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
    },
    hubCardTitle: {
      fontSize: theme.Typography.bodyLarge.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
      marginBottom: 4,
    },
    hubCardDesc: {
      fontSize: theme.Typography.bodySmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      lineHeight: 17,
    },
    sectionContainer: {
      flex: 1,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 18,
    },
    sectionTitle: {
      ...theme.Typography.titleLarge,
      color: theme.Colors.onSurface,
    },
    sectionSub: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurfaceVariant,
      marginTop: 2,
    },
    rolesGrid: {
      gap: 14,
    },
    roleCard: {
      padding: 16,
      borderRadius: 18,
    },
    roleCardTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 10,
      gap: 12,
    },
    roleTitleGroup: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    roleNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 6,
    },
    roleName: {
      fontSize: theme.Typography.bodyLarge.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
      flexShrink: 1,
    },
    roleDesc: {
      fontSize: theme.Typography.bodySmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      lineHeight: 18,
    },
    roleBadgeRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 2,
    },
    customRolePill: {
      backgroundColor: 'rgba(0, 104, 117, 0.08)',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'rgba(0, 104, 117, 0.2)',
      alignSelf: 'flex-start',
      maxWidth: '100%',
    },
    customRolePillText: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
    },
    systemRolePill: {
      backgroundColor: 'rgba(107, 122, 125, 0.08)',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'rgba(107, 122, 125, 0.2)',
      alignSelf: 'flex-start',
      maxWidth: '100%',
    },
    systemRolePillText: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurfaceVariant,
    },
    roleCardBottom: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 14,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: isDark ? 'rgba(255, 255, 255, 0.08)' : 'rgba(0, 0, 0, 0.06)',
      flexWrap: 'wrap',
      gap: 10,
    },
    permCountTag: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'rgba(0, 104, 117, 0.06)',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
    },
    permCountText: {
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
    },
    configureBtn: {
      minHeight: 44,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.Colors.surfaceContainerLowest,
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
    },
    configureBtnDisabled: {
      backgroundColor: theme.Colors.surfaceContainerLow,
    },
    configureBtnText: {
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
    },
    configureBtnTextDisabled: {
      color: theme.Colors.onSurfaceVariant,
    },
    invitesGrid: {
      gap: 14,
    },
    inviteCard: {
      padding: 20,
      borderRadius: 18,
    },
    inviteCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    codeCapsule: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(0, 104, 117, 0.08)',
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'rgba(0, 104, 117, 0.2)',
    },
    inviteCode: {
      fontSize: theme.Typography.bodyLarge.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
      letterSpacing: 1.5,
    },
    inviteMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      marginBottom: 16,
    },
    inviteMetaCol: {
      flex: 1,
      minWidth: 120,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.04)' : 'rgba(255, 255, 255, 0.6)',
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
    },
    inviteMetaLabel: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurfaceVariant,
      marginBottom: 4,
      letterSpacing: 0.8,
    },
    inviteMetaVal: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
    },
    copyKeyBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 44,
      gap: 8,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 22,
      backgroundColor: theme.Colors.surfaceContainerLowest,
      borderWidth: 1,
      borderColor: 'rgba(0, 104, 117, 0.3)',
    },
    copyKeyBtnText: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
    },
    prefGrid: {
      gap: 16,
    },
    prefCard: {
      padding: 22,
      borderRadius: 20,
    },
    prefCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 16,
    },
    prefCardTitle: {
      fontSize: theme.Typography.bodyLarge.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
    },
    prefItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 14,
      borderTopWidth: 1,
      borderTopColor: 'rgba(0, 0, 0, 0.05)',
    },
    prefItemName: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
    },
    prefItemDesc: {
      fontSize: theme.Typography.bodySmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      marginTop: 2,
    },
    prefBadgeActive: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 10,
      backgroundColor: 'rgba(0, 104, 117, 0.08)',
      borderWidth: 1,
      borderColor: 'rgba(0, 104, 117, 0.2)',
    },
    prefBadgeText: {
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.primary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.Colors.modalOverlayBackground || theme.Colors.scrim || 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalCard: {
      width: '100%',
      maxWidth: 640,
      maxHeight: '85%',
      backgroundColor: theme.Colors.surfaceContainerLowest,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.Colors.outline,
      overflow: 'hidden',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingVertical: 18,
      borderBottomWidth: 1,
      borderBottomColor: theme.Colors.outline,
    },
    modalTitle: {
      fontSize: theme.Typography.bodyLg?.fontSize || 18,
      fontWeight: '600',
      color: theme.Colors.onSurface,
    },
    modalSub: {
      fontSize: theme.Typography.bodySmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      marginTop: 2,
    },
    closeIconBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.Colors.surfaceContainer,
    },
    modalBody: {
      padding: 24,
    },
    categoryBlock: {
      marginBottom: 20,
    },
    categoryHeading: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurfaceVariant,
      letterSpacing: 0.2,
      marginBottom: 10,
    },
    permCheckRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(0, 0, 0, 0.04)',
    },
    permCheckRowDisabled: {
      opacity: 0.4,
    },
    permCheckInfo: {
      flex: 1,
      paddingRight: 12,
    },
    permCheckName: {
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurface,
    },
    permCheckNameDisabled: {
      color: theme.Colors.onSurfaceVariant,
    },
    permCheckDesc: {
      fontSize: theme.Typography.bodySmall.fontSize,
      color: theme.Colors.onSurfaceVariant,
      marginTop: 2,
    },
    inputLabel: {
      fontSize: theme.Typography.labelSmall.fontSize,
      fontWeight: '600',
      letterSpacing: 1.1,
      color: theme.Colors.onSurfaceVariant,
      marginBottom: 6,
    },
    modalTextInput: {
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurface,
      backgroundColor: theme.Colors.surfaceContainerLow,
      marginBottom: 16,
    },
    roleChipsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 16,
    },
    roleSelectChip: {
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: theme.Colors.outlineVariant,
      backgroundColor: theme.Colors.surfaceContainerLow,
    },
    roleSelectChipActive: {
      borderColor: theme.Colors.primary,
      backgroundColor: 'rgba(0, 104, 117, 0.08)',
    },
    roleSelectChipText: {
      fontSize: theme.Typography.bodySmall.fontSize,
      fontWeight: '600',
      color: theme.Colors.onSurfaceVariant,
    },
    roleSelectChipTextActive: {
      color: theme.Colors.primary,
    },
    modalFooter: {
      padding: 20,
      borderTopWidth: 1,
      borderTopColor: theme.Colors.outline,
    },
    modalPrimaryBtn: {
      borderRadius: 24,
      overflow: 'hidden',
    },
    modalBtnGradient: {
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 48,
      paddingVertical: 12,
      paddingHorizontal: 20,
      backgroundColor: theme.Colors.primary,
      borderRadius: 24,
    },
    modalBtnText: {
      color: theme.Colors.surfaceContainerLowest,
      fontSize: theme.Typography.bodyMedium.fontSize,
      fontWeight: '600',
      letterSpacing: 0.8,
    },
    centerLoading: {
      padding: 48,
      alignItems: 'center',
      justifyContent: 'center',
    },
    loadingSub: {
      marginTop: 12,
      fontSize: theme.Typography.bodyMedium.fontSize,
      color: theme.Colors.onSurfaceVariant,
    },
  });
